
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pt' | 'es' | 'fr' | 'de';

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  translations: Record<string, Record<string, string>>;
  t: (key: string) => string;
};

const translations = {
  en: {
    // Common
    "app.name": "LeadShield",
    "app.tagline": "Protect Your Business from Fraudulent Leads",
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.leads": "Leads",
    "nav.features": "Features",
    "nav.billing": "Billing",
    "nav.settings": "Settings",
    "nav.about": "About",
    "nav.blog": "Blog",
    "nav.careers": "Careers",
    "nav.contact": "Contact",
    "nav.success_stories": "Success Stories",
    "nav.login": "Log In",
    "nav.signup": "Sign Up Free",
    "nav.logout": "Log out",
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account settings and preferences",
    "settings.account": "Account",
    "settings.scoreConfig": "Score Configuration",
    "settings.notifications": "Notifications",
    "settings.api": "API Keys",
    "settings.score.threshold": "Threshold",
    "settings.score.rules": "Scoring Rules",
    "settings.score.addRule": "Add Rule",
    "settings.score.editRule": "Edit Rule",
    "settings.score.ruleName": "Rule Name",
    "settings.score.ruleDesc": "Description",
    "settings.score.saveConfig": "Save Configuration",
    "settings.score.weight": "Weight",
    // Homepage
    "home.hero.subtitle": "LeadShield uses AI-powered scoring to identify and block suspicious leads before they waste your time and resources.",
    "home.hero.cta.learn": "Learn More",
    "home.hero.benefits.nocredit": "No credit card required",
    "home.hero.benefits.cancel": "Cancel anytime",
    "home.hero.dashboard": "Lead Shield Dashboard",
    "home.hero.realtime": "Real-time protection",
    "home.features.subtitle": "Everything you need to protect your business from fraudulent leads",
    "home.features.scoring.title": "Intelligent Scoring",
    "home.features.scoring.desc": "Our AI-powered algorithm analyzes multiple data points to assign a risk score to each lead.",
    "home.features.rules.title": "Custom Rules",
    "home.features.rules.desc": "Create and customize scoring rules based on your unique business needs and requirements.",
    "home.features.team.title": "Team Collaboration",
    "home.features.team.desc": "Add team members with different roles and permissions to manage leads collectively.",
    "home.features.billing.title": "Flexible Billing",
    "home.features.billing.desc": "Choose between monthly and annual billing with plans that scale as your business grows.",
    "home.features.protection.title": "Real-time Protection",
    "home.features.protection.desc": "Identify and block suspicious leads in real-time before they enter your sales funnel.",
    "home.features.api.title": "API Integration",
    "home.features.api.desc": "Seamlessly integrate with your existing CRM, marketing tools, and other software systems.",
    "home.about.subtitle": "The story behind LeadShield",
    "home.about.name": "Fernando Ramalho",
    "home.about.quote": "\"I founded LeadShield after experiencing the frustration of wasted time and resources on fraudulent leads in my previous business. I knew there had to be a better way to protect companies from this common problem.\"",
    "home.about.bio1": "With over 8 years of experience in marketing and lead generation, Fernando identified a critical gap in the market: the lack of robust tools to detect and prevent fraudulent leads before they waste valuable time and resources.",
    "home.about.bio2": "Since launching LeadShield, Fernando has led the company in protecting thousands of businesses around the world, helping them save time, money, and focus on genuine growth opportunities.",
    "home.about.role": "Fernando Ramalho, Founder & CEO",
    "home.about.cta": "Learn More About Us",
    "home.pricing.subtitle": "Choose the perfect plan for your business needs",
    "home.pricing.free.name": "Free",
    "home.pricing.free.desc": "Get started with basic lead protection",
    "home.pricing.free.feature1": "Up to 100 leads/month",
    "home.pricing.free.feature2": "Basic lead scoring", 
    "home.pricing.free.feature3": "Email support",
    "home.pricing.start.name": "Start",
    "home.pricing.start.desc": "Protection for growing businesses",
    "home.pricing.start.feature1": "Up to 500 leads/month",
    "home.pricing.start.feature2": "Custom scoring rules (2)",
    "home.pricing.start.feature3": "Team members (2)",
    "home.pricing.growth.tag": "Most Popular",
    "home.pricing.growth.name": "Growth",
    "home.pricing.growth.desc": "Advanced protection & analytics",
    "home.pricing.growth.feature1": "Up to 2,000 leads/month",
    "home.pricing.growth.feature2": "Custom scoring rules (5)",
    "home.pricing.growth.feature3": "Team members (5)",
    "home.pricing.growth.feature4": "Advanced analytics",
    "home.pricing.full.name": "Full Shield",
    "home.pricing.full.desc": "Enterprise-grade protection",
    "home.pricing.full.feature1": "Unlimited leads",
    "home.pricing.full.feature2": "Unlimited custom rules",
    "home.pricing.full.feature3": "Unlimited team members",
    "home.pricing.full.feature4": "24/7 priority support",
    "home.pricing.cta": "Get Started",
    "home.cta.title": "Ready to protect your business?",
    "home.cta.subtitle": "Start using LeadShield today and stop wasting time and resources on fraudulent leads.",
    "footer.resources": "Resources",
    "footer.docs": "Documentation",
    "footer.support": "Support",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.company": "Company",
    "footer.copyright": "All rights reserved."
  },
  pt: {
    // Common
    "app.name": "LeadShield",
    "app.tagline": "Proteja seu Negócio de Leads Fraudulentos",
    // Navigation
    "nav.dashboard": "Painel",
    "nav.leads": "Leads",
    "nav.features": "Recursos",
    "nav.billing": "Cobrança",
    "nav.settings": "Configurações",
    "nav.about": "Sobre",
    "nav.blog": "Blog",
    "nav.careers": "Carreiras",
    "nav.contact": "Contato",
    "nav.success_stories": "Histórias de Sucesso",
    "nav.login": "Entrar",
    "nav.signup": "Cadastre-se Grátis",
    "nav.logout": "Sair",
    // Settings
    "settings.title": "Configurações",
    "settings.subtitle": "Gerencie suas configurações e preferências de conta",
    "settings.account": "Conta",
    "settings.scoreConfig": "Configuração de Pontuação",
    "settings.notifications": "Notificações",
    "settings.api": "Chaves API",
    "settings.score.threshold": "Limite",
    "settings.score.rules": "Regras de Pontuação",
    "settings.score.addRule": "Adicionar Regra",
    "settings.score.editRule": "Editar Regra",
    "settings.score.ruleName": "Nome da Regra",
    "settings.score.ruleDesc": "Descrição",
    "settings.score.saveConfig": "Salvar Configuração",
    "settings.score.weight": "Peso",
    // Homepage
    "home.hero.subtitle": "LeadShield usa pontuação baseada em IA para identificar e bloquear leads suspeitos antes que eles desperdicem seu tempo e recursos.",
    "home.hero.cta.learn": "Saiba Mais",
    "home.hero.benefits.nocredit": "Sem necessidade de cartão de crédito",
    "home.hero.benefits.cancel": "Cancele quando quiser",
    "home.hero.dashboard": "Painel LeadShield",
    "home.hero.realtime": "Proteção em tempo real",
    "home.features.subtitle": "Tudo o que você precisa para proteger seu negócio de leads fraudulentos",
    "home.features.scoring.title": "Pontuação Inteligente",
    "home.features.scoring.desc": "Nosso algoritmo baseado em IA analisa múltiplos pontos de dados para atribuir uma pontuação de risco a cada lead.",
    "home.features.rules.title": "Regras Personalizadas",
    "home.features.rules.desc": "Crie e personalize regras de pontuação com base nas necessidades e requisitos exclusivos do seu negócio.",
    "home.features.team.title": "Colaboração em Equipe",
    "home.features.team.desc": "Adicione membros da equipe com diferentes funções e permissões para gerenciar leads coletivamente.",
    "home.features.billing.title": "Cobrança Flexível",
    "home.features.billing.desc": "Escolha entre cobrança mensal e anual com planos que crescem conforme seu negócio.",
    "home.features.protection.title": "Proteção em Tempo Real",
    "home.features.protection.desc": "Identifique e bloqueie leads suspeitos em tempo real antes que entrem no seu funil de vendas.",
    "home.features.api.title": "Integração API",
    "home.features.api.desc": "Integre perfeitamente com seu CRM existente, ferramentas de marketing e outros sistemas de software.",
    "home.about.subtitle": "A história por trás do LeadShield",
    "home.about.name": "Fernando Ramalho",
    "home.about.quote": "\"Fundei o LeadShield após experimentar a frustração do tempo e recursos desperdiçados com leads fraudulentos em meu negócio anterior. Eu sabia que deveria haver uma maneira melhor de proteger as empresas desse problema comum.\"",
    "home.about.bio1": "Com mais de 8 anos de experiência em marketing e geração de leads, Fernando identificou uma lacuna crítica no mercado: a falta de ferramentas robustas para detectar e prevenir leads fraudulentos antes que desperdicem tempo e recursos valiosos.",
    "home.about.bio2": "Desde o lançamento do LeadShield, Fernando liderou a empresa na proteção de milhares de negócios em todo o mundo, ajudando-os a economizar tempo, dinheiro e focar em oportunidades genuínas de crescimento.",
    "home.about.role": "Fernando Ramalho, Fundador & CEO",
    "home.about.cta": "Saiba Mais Sobre Nós",
    "home.pricing.subtitle": "Escolha o plano perfeito para as necessidades do seu negócio",
    "home.pricing.free.name": "Gratuito",
    "home.pricing.free.desc": "Comece com proteção básica de leads",
    "home.pricing.free.feature1": "Até 100 leads/mês",
    "home.pricing.free.feature2": "Pontuação básica de leads", 
    "home.pricing.free.feature3": "Suporte por e-mail",
    "home.pricing.start.name": "Inicial",
    "home.pricing.start.desc": "Proteção para negócios em crescimento",
    "home.pricing.start.feature1": "Até 500 leads/mês",
    "home.pricing.start.feature2": "Regras personalizadas (2)",
    "home.pricing.start.feature3": "Membros da equipe (2)",
    "home.pricing.growth.tag": "Mais Popular",
    "home.pricing.growth.name": "Crescimento",
    "home.pricing.growth.desc": "Proteção avançada e análises",
    "home.pricing.growth.feature1": "Até 2.000 leads/mês",
    "home.pricing.growth.feature2": "Regras personalizadas (5)",
    "home.pricing.growth.feature3": "Membros da equipe (5)",
    "home.pricing.growth.feature4": "Análises avançadas",
    "home.pricing.full.name": "Proteção Total",
    "home.pricing.full.desc": "Proteção nível empresarial",
    "home.pricing.full.feature1": "Leads ilimitados",
    "home.pricing.full.feature2": "Regras personalizadas ilimitadas",
    "home.pricing.full.feature3": "Membros da equipe ilimitados",
    "home.pricing.full.feature4": "Suporte prioritário 24/7",
    "home.pricing.cta": "Começar",
    "home.cta.title": "Pronto para proteger seu negócio?",
    "home.cta.subtitle": "Comece a usar o LeadShield hoje e pare de desperdiçar tempo e recursos com leads fraudulentos.",
    "footer.resources": "Recursos",
    "footer.docs": "Documentação",
    "footer.support": "Suporte",
    "footer.privacy": "Privacidade",
    "footer.terms": "Termos",
    "footer.company": "Empresa",
    "footer.copyright": "Todos os direitos reservados."
  },
  es: {
    // Common
    "app.name": "LeadShield",
    "app.tagline": "Proteja su Negocio de Leads Fraudulentos",
    // Navigation
    "nav.dashboard": "Panel",
    "nav.leads": "Leads",
    "nav.features": "Características",
    "nav.billing": "Facturación",
    "nav.settings": "Configuración",
    "nav.about": "Acerca de",
    "nav.blog": "Blog",
    "nav.careers": "Carreras",
    "nav.contact": "Contacto",
    "nav.success_stories": "Casos de Éxito",
    "nav.login": "Iniciar Sesión",
    "nav.signup": "Registrarse Gratis",
    "nav.logout": "Cerrar Sesión",
    // Settings
    "settings.title": "Configuración",
    "settings.subtitle": "Administre su configuración y preferencias de cuenta",
    "settings.account": "Cuenta",
    "settings.scoreConfig": "Configuración de Puntuación",
    "settings.notifications": "Notificaciones",
    "settings.api": "Claves API",
    "settings.score.threshold": "Umbral",
    "settings.score.rules": "Reglas de Puntuación",
    "settings.score.addRule": "Añadir Regla",
    "settings.score.editRule": "Editar Regla",
    "settings.score.ruleName": "Nombre de Regla",
    "settings.score.ruleDesc": "Descripción",
    "settings.score.saveConfig": "Guardar Configuración",
    "settings.score.weight": "Peso",
    // Homepage
    "home.hero.subtitle": "LeadShield utiliza puntuación basada en IA para identificar y bloquear leads sospechosos antes de que desperdicien su tiempo y recursos.",
    "home.hero.cta.learn": "Saber Más",
    "home.hero.benefits.nocredit": "No se requiere tarjeta de crédito",
    "home.hero.benefits.cancel": "Cancele cuando quiera",
    "home.hero.dashboard": "Panel de LeadShield",
    "home.hero.realtime": "Protección en tiempo real",
    "home.features.subtitle": "Todo lo que necesita para proteger su negocio de leads fraudulentos",
    "home.features.scoring.title": "Puntuación Inteligente",
    "home.features.scoring.desc": "Nuestro algoritmo basado en IA analiza múltiples puntos de datos para asignar una puntuación de riesgo a cada lead.",
    "home.features.rules.title": "Reglas Personalizadas",
    "home.features.rules.desc": "Cree y personalice reglas de puntuación basadas en las necesidades y requisitos únicos de su negocio.",
    "home.features.team.title": "Colaboración en Equipo",
    "home.features.team.desc": "Añada miembros del equipo con diferentes roles y permisos para gestionar leads colectivamente.",
    "home.features.billing.title": "Facturación Flexible",
    "home.features.billing.desc": "Elija entre facturación mensual y anual con planes que escalan a medida que su negocio crece.",
    "home.features.protection.title": "Protección en Tiempo Real",
    "home.features.protection.desc": "Identifique y bloquee leads sospechosos en tiempo real antes de que entren en su embudo de ventas.",
    "home.features.api.title": "Integración API",
    "home.features.api.desc": "Intégrese perfectamente con su CRM existente, herramientas de marketing y otros sistemas de software.",
    "home.about.subtitle": "La historia detrás de LeadShield",
    "home.about.name": "Fernando Ramalho",
    "home.about.quote": "\"Fundé LeadShield después de experimentar la frustración del tiempo y recursos desperdiciados en leads fraudulentos en mi negocio anterior. Sabía que debía haber una mejor manera de proteger a las empresas de este problema común.\"",
    "home.about.bio1": "Con más de 8 años de experiencia en marketing y generación de leads, Fernando identificó una brecha crítica en el mercado: la falta de herramientas robustas para detectar y prevenir leads fraudulentos antes de que desperdicien tiempo y recursos valiosos.",
    "home.about.bio2": "Desde el lanzamiento de LeadShield, Fernando ha liderado la compañía en la protección de miles de negocios alrededor del mundo, ayudándoles a ahorrar tiempo, dinero y enfocarse en oportunidades genuinas de crecimiento.",
    "home.about.role": "Fernando Ramalho, Fundador & CEO",
    "home.about.cta": "Conozca Más Sobre Nosotros",
    "home.pricing.subtitle": "Elija el plan perfecto para las necesidades de su negocio",
    "home.pricing.free.name": "Gratis",
    "home.pricing.free.desc": "Comience con protección básica de leads",
    "home.pricing.free.feature1": "Hasta 100 leads/mes",
    "home.pricing.free.feature2": "Puntuación básica de leads", 
    "home.pricing.free.feature3": "Soporte por correo electrónico",
    "home.pricing.start.name": "Inicio",
    "home.pricing.start.desc": "Protección para negocios en crecimiento",
    "home.pricing.start.feature1": "Hasta 500 leads/mes",
    "home.pricing.start.feature2": "Reglas personalizadas (2)",
    "home.pricing.start.feature3": "Miembros del equipo (2)",
    "home.pricing.growth.tag": "Más Popular",
    "home.pricing.growth.name": "Crecimiento",
    "home.pricing.growth.desc": "Protección avanzada y análisis",
    "home.pricing.growth.feature1": "Hasta 2.000 leads/mes",
    "home.pricing.growth.feature2": "Reglas personalizadas (5)",
    "home.pricing.growth.feature3": "Miembros del equipo (5)",
    "home.pricing.growth.feature4": "Análisis avanzados",
    "home.pricing.full.name": "Protección Total",
    "home.pricing.full.desc": "Protección a nivel empresarial",
    "home.pricing.full.feature1": "Leads ilimitados",
    "home.pricing.full.feature2": "Reglas personalizadas ilimitadas",
    "home.pricing.full.feature3": "Miembros del equipo ilimitados",
    "home.pricing.full.feature4": "Soporte prioritario 24/7",
    "home.pricing.cta": "Comenzar",
    "home.cta.title": "¿Listo para proteger su negocio?",
    "home.cta.subtitle": "Comience a usar LeadShield hoy y deje de perder tiempo y recursos en leads fraudulentos.",
    "footer.resources": "Recursos",
    "footer.docs": "Documentación",
    "footer.support": "Soporte",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.company": "Empresa",
    "footer.copyright": "Todos los derechos reservados."
  },
  fr: {
    // Common
    "app.name": "LeadShield",
    "app.tagline": "Protégez Votre Entreprise Contre les Leads Frauduleux",
    // Navigation
    "nav.dashboard": "Tableau de Bord",
    "nav.leads": "Leads",
    "nav.features": "Fonctionnalités",
    "nav.billing": "Facturation",
    "nav.settings": "Paramètres",
    "nav.about": "À Propos",
    "nav.blog": "Blog",
    "nav.careers": "Carrières",
    "nav.contact": "Contact",
    "nav.success_stories": "Témoignages",
    "nav.login": "Connexion",
    "nav.signup": "Inscription Gratuite",
    "nav.logout": "Déconnexion",
    // Settings
    "settings.title": "Paramètres",
    "settings.subtitle": "Gérez vos paramètres et préférences de compte",
    "settings.account": "Compte",
    "settings.scoreConfig": "Configuration de Score",
    "settings.notifications": "Notifications",
    "settings.api": "Clés API",
    "settings.score.threshold": "Seuil",
    "settings.score.rules": "Règles de Scoring",
    "settings.score.addRule": "Ajouter une Règle",
    "settings.score.editRule": "Modifier la Règle",
    "settings.score.ruleName": "Nom de la Règle",
    "settings.score.ruleDesc": "Description",
    "settings.score.saveConfig": "Enregistrer la Configuration",
    "settings.score.weight": "Poids",
    // Homepage
    "home.hero.subtitle": "LeadShield utilise un scoring basé sur l'IA pour identifier et bloquer les leads suspects avant qu'ils ne gaspillent votre temps et vos ressources.",
    "home.hero.cta.learn": "En Savoir Plus",
    "home.hero.benefits.nocredit": "Pas de carte de crédit requise",
    "home.hero.benefits.cancel": "Annulez quand vous voulez",
    "home.hero.dashboard": "Tableau de bord LeadShield",
    "home.hero.realtime": "Protection en temps réel",
    "home.features.subtitle": "Tout ce dont vous avez besoin pour protéger votre entreprise des leads frauduleux",
    "home.features.scoring.title": "Scoring Intelligent",
    "home.features.scoring.desc": "Notre algorithme basé sur l'IA analyse de multiples points de données pour attribuer un score de risque à chaque lead.",
    "home.features.rules.title": "Règles Personnalisées",
    "home.features.rules.desc": "Créez et personnalisez des règles de scoring en fonction des besoins et exigences uniques de votre entreprise.",
    "home.features.team.title": "Collaboration d'Équipe",
    "home.features.team.desc": "Ajoutez des membres d'équipe avec différents rôles et permissions pour gérer collectivement les leads.",
    "home.features.billing.title": "Facturation Flexible",
    "home.features.billing.desc": "Choisissez entre facturation mensuelle et annuelle avec des plans qui évoluent avec votre entreprise.",
    "home.features.protection.title": "Protection en Temps Réel",
    "home.features.protection.desc": "Identifiez et bloquez les leads suspects en temps réel avant qu'ils n'entrent dans votre entonnoir de vente.",
    "home.features.api.title": "Intégration API",
    "home.features.api.desc": "Intégrez-vous parfaitement avec votre CRM existant, vos outils marketing et autres systèmes logiciels.",
    "home.about.subtitle": "L'histoire derrière LeadShield",
    "home.about.name": "Fernando Ramalho",
    "home.about.quote": "\"J'ai fondé LeadShield après avoir vécu la frustration du temps et des ressources gaspillés sur des leads frauduleux dans mon entreprise précédente. Je savais qu'il devait y avoir une meilleure façon de protéger les entreprises de ce problème courant.\"",
    "home.about.bio1": "Avec plus de 8 ans d'expérience en marketing et génération de leads, Fernando a identifié une lacune critique sur le marché : l'absence d'outils robustes pour détecter et prévenir les leads frauduleux avant qu'ils ne gaspillent du temps et des ressources précieux.",
    "home.about.bio2": "Depuis le lancement de LeadShield, Fernando a dirigé l'entreprise dans la protection de milliers d'entreprises à travers le monde, les aidant à économiser du temps, de l'argent et à se concentrer sur de véritables opportunités de croissance.",
    "home.about.role": "Fernando Ramalho, Fondateur & PDG",
    "home.about.cta": "En Savoir Plus Sur Nous",
    "home.pricing.subtitle": "Choisissez le plan parfait pour les besoins de votre entreprise",
    "home.pricing.free.name": "Gratuit",
    "home.pricing.free.desc": "Commencez avec une protection de base des leads",
    "home.pricing.free.feature1": "Jusqu'à 100 leads/mois",
    "home.pricing.free.feature2": "Scoring de base des leads", 
    "home.pricing.free.feature3": "Support par email",
    "home.pricing.start.name": "Démarrage",
    "home.pricing.start.desc": "Protection pour entreprises en croissance",
    "home.pricing.start.feature1": "Jusqu'à 500 leads/mois",
    "home.pricing.start.feature2": "Règles personnalisées (2)",
    "home.pricing.start.feature3": "Membres d'équipe (2)",
    "home.pricing.growth.tag": "Le Plus Populaire",
    "home.pricing.growth.name": "Croissance",
    "home.pricing.growth.desc": "Protection avancée et analyses",
    "home.pricing.growth.feature1": "Jusqu'à 2 000 leads/mois",
    "home.pricing.growth.feature2": "Règles personnalisées (5)",
    "home.pricing.growth.feature3": "Membres d'équipe (5)",
    "home.pricing.growth.feature4": "Analyses avancées",
    "home.pricing.full.name": "Protection Complète",
    "home.pricing.full.desc": "Protection niveau entreprise",
    "home.pricing.full.feature1": "Leads illimités",
    "home.pricing.full.feature2": "Règles personnalisées illimitées",
    "home.pricing.full.feature3": "Membres d'équipe illimités",
    "home.pricing.full.feature4": "Support prioritaire 24/7",
    "home.pricing.cta": "Commencer",
    "home.cta.title": "Prêt à protéger votre entreprise ?",
    "home.cta.subtitle": "Commencez à utiliser LeadShield aujourd'hui et arrêtez de perdre du temps et des ressources sur des leads frauduleux.",
    "footer.resources": "Ressources",
    "footer.docs": "Documentation",
    "footer.support": "Support",
    "footer.privacy": "Confidentialité",
    "footer.terms": "Conditions",
    "footer.company": "Entreprise",
    "footer.copyright": "Tous droits réservés."
  },
  de: {
    // Common
    "app.name": "LeadShield",
    "app.tagline": "Schützen Sie Ihr Unternehmen vor betrügerischen Leads",
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.leads": "Leads",
    "nav.features": "Funktionen",
    "nav.billing": "Abrechnung",
    "nav.settings": "Einstellungen",
    "nav.about": "Über uns",
    "nav.blog": "Blog",
    "nav.careers": "Karriere",
    "nav.contact": "Kontakt",
    "nav.success_stories": "Erfolgsgeschichten",
    "nav.login": "Anmelden",
    "nav.signup": "Kostenlos Registrieren",
    "nav.logout": "Abmelden",
    // Settings
    "settings.title": "Einstellungen",
    "settings.subtitle": "Verwalten Sie Ihre Kontoeinstellungen und Präferenzen",
    "settings.account": "Konto",
    "settings.scoreConfig": "Score-Konfiguration",
    "settings.notifications": "Benachrichtigungen",
    "settings.api": "API-Schlüssel",
    "settings.score.threshold": "Schwellenwert",
    "settings.score.rules": "Scoring-Regeln",
    "settings.score.addRule": "Regel hinzufügen",
    "settings.score.editRule": "Regel bearbeiten",
    "settings.score.ruleName": "Regelname",
    "settings.score.ruleDesc": "Beschreibung",
    "settings.score.saveConfig": "Konfiguration speichern",
    "settings.score.weight": "Gewichtung",
    // Homepage
    "home.hero.subtitle": "LeadShield verwendet KI-gestützte Bewertung, um verdächtige Leads zu identifizieren und zu blockieren, bevor sie Ihre Zeit und Ressourcen verschwenden.",
    "home.hero.cta.learn": "Mehr Erfahren",
    "home.hero.benefits.nocredit": "Keine Kreditkarte erforderlich",
    "home.hero.benefits.cancel": "Jederzeit kündbar",
    "home.hero.dashboard": "LeadShield Dashboard",
    "home.hero.realtime": "Echtzeit-Schutz",
    "home.features.subtitle": "Alles, was Sie benötigen, um Ihr Unternehmen vor betrügerischen Leads zu schützen",
    "home.features.scoring.title": "Intelligente Bewertung",
    "home.features.scoring.desc": "Unser KI-gestützter Algorithmus analysiert mehrere Datenpunkte, um jedem Lead eine Risikobewertung zuzuweisen.",
    "home.features.rules.title": "Benutzerdefinierte Regeln",
    "home.features.rules.desc": "Erstellen und passen Sie Bewertungsregeln basierend auf den einzigartigen Bedürfnissen und Anforderungen Ihres Unternehmens an.",
    "home.features.team.title": "Team-Zusammenarbeit",
    "home.features.team.desc": "Fügen Sie Teammitglieder mit verschiedenen Rollen und Berechtigungen hinzu, um Leads gemeinsam zu verwalten.",
    "home.features.billing.title": "Flexible Abrechnung",
    "home.features.billing.desc": "Wählen Sie zwischen monatlicher und jährlicher Abrechnung mit Plänen, die mit Ihrem Unternehmen wachsen.",
    "home.features.protection.title": "Echtzeit-Schutz",
    "home.features.protection.desc": "Identifizieren und blockieren Sie verdächtige Leads in Echtzeit, bevor sie in Ihren Verkaufstrichter gelangen.",
    "home.features.api.title": "API-Integration",
    "home.features.api.desc": "Nahtlose Integration mit Ihrem bestehenden CRM, Marketing-Tools und anderen Softwaresystemen.",
    "home.about.subtitle": "Die Geschichte hinter LeadShield",
    "home.about.name": "Fernando Ramalho",
    "home.about.quote": "\"Ich habe LeadShield gegründet, nachdem ich in meinem vorherigen Unternehmen die Frustration von verschwendeter Zeit und Ressourcen durch betrügerische Leads erlebt habe. Ich wusste, dass es einen besseren Weg geben musste, Unternehmen vor diesem häufigen Problem zu schützen.\"",
    "home.about.bio1": "Mit über 8 Jahren Erfahrung im Marketing und in der Lead-Generierung identifizierte Fernando eine kritische Marktlücke: das Fehlen robuster Tools zur Erkennung und Verhinderung betrügerischer Leads, bevor sie wertvolle Zeit und Ressourcen verschwenden.",
    "home.about.bio2": "Seit der Gründung von LeadShield hat Fernando das Unternehmen beim Schutz tausender Unternehmen weltweit geführt und ihnen geholfen, Zeit und Geld zu sparen und sich auf echte Wachstumschancen zu konzentrieren.",
    "home.about.role": "Fernando Ramalho, Gründer & CEO",
    "home.about.cta": "Mehr Über Uns Erfahren",
    "home.pricing.subtitle": "Wählen Sie den perfekten Plan für die Bedürfnisse Ihres Unternehmens",
    "home.pricing.free.name": "Kostenlos",
    "home.pricing.free.desc": "Starten Sie mit grundlegendem Lead-Schutz",
    "home.pricing.free.feature1": "Bis zu 100 Leads/Monat",
    "home.pricing.free.feature2": "Grundlegende Lead-Bewertung", 
    "home.pricing.free.feature3": "E-Mail-Support",
    "home.pricing.start.name": "Start",
    "home.pricing.start.desc": "Schutz für wachsende Unternehmen",
    "home.pricing.start.feature1": "Bis zu 500 Leads/Monat",
    "home.pricing.start.feature2": "Benutzerdefinierte Regeln (2)",
    "home.pricing.start.feature3": "Teammitglieder (2)",
    "home.pricing.growth.tag": "Am Beliebtesten",
    "home.pricing.growth.name": "Wachstum",
    "home.pricing.growth.desc": "Erweiterter Schutz und Analysen",
    "home.pricing.growth.feature1": "Bis zu 2.000 Leads/Monat",
    "home.pricing.growth.feature2": "Benutzerdefinierte Regeln (5)",
    "home.pricing.growth.feature3": "Teammitglieder (5)",
    "home.pricing.growth.feature4": "Erweiterte Analysen",
    "home.pricing.full.name": "Vollständiger Schutz",
    "home.pricing.full.desc": "Unternehmensfähiger Schutz",
    "home.pricing.full.feature1": "Unbegrenzte Leads",
    "home.pricing.full.feature2": "Unbegrenzte benutzerdefinierte Regeln",
    "home.pricing.full.feature3": "Unbegrenzte Teammitglieder",
    "home.pricing.full.feature4": "Prioritätssupport rund um die Uhr",
    "home.pricing.cta": "Jetzt Starten",
    "home.cta.title": "Bereit, Ihr Unternehmen zu schützen?",
    "home.cta.subtitle": "Beginnen Sie noch heute mit LeadShield und verschwenden Sie keine Zeit und Ressourcen mehr für betrügerische Leads.",
    "footer.resources": "Ressourcen",
    "footer.docs": "Dokumentation",
    "footer.support": "Support",
    "footer.privacy": "Datenschutz",
    "footer.terms": "Nutzungsbedingungen",
    "footer.company": "Unternehmen",
    "footer.copyright": "Alle Rechte vorbehalten."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  // Try to get language from localStorage, default to 'en'
  const [language, setLanguage] = useState<Language>(() => {
    const storedLanguage = localStorage.getItem('leadshield-language');
    return (storedLanguage as Language) || 
           (navigator.language.startsWith('pt') ? 'pt' : 
            navigator.language.startsWith('es') ? 'es' : 
            navigator.language.startsWith('fr') ? 'fr' : 
            navigator.language.startsWith('de') ? 'de' : 'en');
  });

  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('leadshield-language', language);
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
