
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pt' | 'es' | 'fr' | 'de';

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  translations: Record<string, Record<string, string>>;
  t: (key: string) => string;
};

const translations = {
  en: {
    // Common
    "app.name": "LeadShield",
    "app.tagline": "Protect Your Business from Fraudulent Leads",
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.leads": "Leads",
    "nav.features": "Features",
    "nav.billing": "Billing",
    "nav.settings": "Settings",
    "nav.about": "About",
    "nav.blog": "Blog",
    "nav.careers": "Careers",
    "nav.contact": "Contact",
    "nav.success_stories": "Success Stories",
    "nav.login": "Log In",
    "nav.signup": "Sign Up Free",
    "nav.logout": "Log out",
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account settings and preferences",
    "settings.account": "Account",
    "settings.scoreConfig": "Score Configuration",
    "settings.notifications": "Notifications",
    "settings.api": "API Keys",
    "settings.score.threshold": "Threshold",
    "settings.score.rules": "Scoring Rules",
    "settings.score.addRule": "Add Rule",
    "settings.score.editRule": "Edit Rule",
    "settings.score.ruleName": "Rule Name",
    "settings.score.ruleDesc": "Description",
    "settings.score.saveConfig": "Save Configuration",
    "settings.score.weight": "Weight",
    // Homepage
    "home.hero.subtitle": "LeadShield uses AI-powered scoring to identify and block suspicious leads before they waste your time and resources.",
    "home.hero.cta.learn": "Learn More",
    "home.hero.benefits.nocredit": "No credit card required",
    "home.hero.benefits.cancel": "Cancel anytime",
    "home.hero.dashboard": "Lead Shield Dashboard",
    "home.hero.realtime": "Real-time protection",
    "home.features.subtitle": "Everything you need to protect your business from fraudulent leads",
    "home.features.scoring.title": "Intelligent Scoring",
    "home.features.scoring.desc": "Our AI-powered algorithm analyzes multiple data points to assign a risk score to each lead.",
    "home.features.rules.title": "Custom Rules",
    "home.features.rules.desc": "Create and customize scoring rules based on your unique business needs and requirements.",
    "home.features.team.title": "Team Collaboration",
    "home.features.team.desc": "Add team members with different roles and permissions to manage leads collectively.",
    "home.features.billing.title": "Flexible Billing",
    "home.features.billing.desc": "Choose between monthly and annual billing with plans that scale as your business grows.",
    "home.features.protection.title": "Real-time Protection",
    "home.features.protection.desc": "Identify and block suspicious leads in real-time before they enter your sales funnel.",
    "home.features.api.title": "API Integration",
    "home.features.api.desc": "Seamlessly integrate with your existing CRM, marketing tools, and other software systems.",
    "home.about.subtitle": "The story behind LeadShield",
    "home.about.name": "Fernando Ramalho",
    "home.about.quote": "\"I founded LeadShield after experiencing the frustration of wasted time and resources on fraudulent leads in my previous business. I knew there had to be a better way to protect companies from this common problem.\"",
    "home.about.bio1": "With over 8 years of experience in marketing and lead generation, Fernando identified a critical gap in the market: the lack of robust tools to detect and prevent fraudulent leads before they waste valuable time and resources.",
    "home.about.bio2": "Since launching LeadShield, Fernando has led the company in protecting thousands of businesses around the world, helping them save time, money, and focus on genuine growth opportunities.",
    "home.about.role": "Fernando Ramalho, Founder & CEO",
    "home.about.cta": "Learn More About Us",
    "home.pricing.subtitle": "Choose the perfect plan for your business needs",
    "home.pricing.free.name": "Free",
    "home.pricing.free.desc": "Get started with basic lead protection",
    "home.pricing.free.feature1": "Up to 100 leads/month",
    "home.pricing.free.feature2": "Basic lead scoring", 
    "home.pricing.free.feature3": "Email support",
    "home.pricing.start.name": "Start",
    "home.pricing.start.desc": "Protection for growing businesses",
    "home.pricing.start.feature1": "Up to 500 leads/month",
    "home.pricing.start.feature2": "Custom scoring rules (2)",
    "home.pricing.start.feature3": "Team members (2)",
    "home.pricing.growth.tag": "Most Popular",
    "home.pricing.growth.name": "Growth",
    "home.pricing.growth.desc": "Advanced protection & analytics",
    "home.pricing.growth.feature1": "Up to 2,000 leads/month",
    "home.pricing.growth.feature2": "Custom scoring rules (5)",
    "home.pricing.growth.feature3": "Team members (5)",
    "home.pricing.growth.feature4": "Advanced analytics",
    "home.pricing.full.name": "Full Shield",
    "home.pricing.full.desc": "Enterprise-grade protection",
    "home.pricing.full.feature1": "Unlimited leads",
    "home.pricing.full.feature2": "Unlimited custom rules",
    "home.pricing.full.feature3": "Unlimited team members",
    "home.pricing.full.feature4": "24/7 priority support",
    "home.pricing.cta": "Get Started",
    "home.cta.title": "Ready to protect your business?",
    "home.cta.subtitle": "Start using LeadShield today and stop wasting time and resources on fraudulent leads.",
    "footer.resources": "Resources",
    "footer.docs": "Documentation",
    "footer.support": "Support",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.company": "Company",
    "footer.copyright": "All rights reserved.",
    
    // Login page
    "login.welcome": "Welcome back",
    "login.enter_credentials": "Enter your credentials to access your account",
    "login.email": "Email",
    "login.email_placeholder": "you@example.com",
    "login.password": "Password",
    "login.password_placeholder": "••••••••",
    "login.logging_in": "Logging in...",
    "login.demo_credentials": "Demo credentials:",
    "login.forgot_password": "Forgot password?",
    
    // Signup page
    "signup.create_account": "Create account",
    "signup.enter_details": "Enter your details to create a new account",
    "signup.full_name": "Full Name",
    "signup.name_placeholder": "John Doe",
    "signup.company_name": "Company Name",
    "signup.company_placeholder": "Your Company",
    "signup.creating_account": "Creating account...",
    "signup.create_button": "Create Account",
    
    // About page
    "about.title": "About LeadShield",
    "about.subtitle": "We're on a mission to help businesses protect themselves from fraudulent leads and focus on genuine opportunities.",
    "about.story.title": "Our Story",
    "about.story.paragraph1": "LeadShield was founded in 2023 after our founder experienced firsthand the frustration of dealing with fake leads that wasted time and resources.",
    "about.story.paragraph2": "What started as an internal tool quickly evolved into a comprehensive platform that helps businesses of all sizes identify and filter out fraudulent leads before they enter the sales funnel.",
    "about.story.paragraph3": "Today, LeadShield protects thousands of businesses worldwide, saving them countless hours and resources that would otherwise be wasted on fake leads.",
    "about.story.office": "Our headquarters in San Francisco, CA",
    "about.mission.title": "Our Mission",
    "about.mission.statement": "To empower businesses with intelligent tools that protect them from fraud and enable them to focus on genuine growth opportunities.",
    "about.mission.attribution": "LeadShield Mission Statement",
    "about.values.title": "Our Values",
    "about.values.protection.title": "Protection",
    "about.values.protection.desc": "We believe in creating robust systems that shield businesses from potential threats and vulnerabilities.",
    "about.values.trust.title": "Trust",
    "about.values.trust.desc": "We build relationships based on transparency, reliability, and consistent delivery of quality service.",
    "about.values.innovation.title": "Innovation",
    "about.values.innovation.desc": "We continuously evolve our technology to stay ahead of emerging threats and provide cutting-edge solutions.",
    
    // Blog page
    "blog.title": "LeadShield Blog",
    "blog.subtitle": "Insights and strategies to protect your business from fraudulent leads",
    "blog.by": "By",
    "blog.read_more": "Read More",
    "blog.categories.lead_management": "Lead Management",
    "blog.categories.business": "Business",
    "blog.categories.technology": "Technology",
    "blog.categories.news": "Company News",
    "blog.categories.lead_generation": "Lead Generation",
    "blog.team": "LeadShield Team",
    "blog.post1.title": "How to Identify Fraudulent Leads: 5 Warning Signs",
    "blog.post1.excerpt": "Learn how to spot fake leads before they waste your time and resources.",
    "blog.post1.date": "May 10, 2024",
    "blog.post2.title": "The True Cost of Fake Leads for Small Businesses",
    "blog.post2.excerpt": "Discover how fraudulent leads impact your bottom line and what you can do about it.",
    "blog.post2.date": "April 25, 2024",
    "blog.post3.title": "AI-Powered Lead Verification: The Future of Sales",
    "blog.post3.excerpt": "See how artificial intelligence is revolutionizing the way businesses validate leads.",
    "blog.post3.date": "April 12, 2024",
    "blog.post4.title": "LeadShield Announces Series A Funding",
    "blog.post4.excerpt": "We're excited to announce our latest round of funding, which will help us expand our reach and continue to innovate.",
    "blog.post4.date": "March 20, 2024",
    "blog.post5.title": "Top 10 Lead Generation Strategies for 2024",
    "blog.post5.excerpt": "Stay ahead of the curve with these proven lead generation techniques.",
    "blog.post5.date": "February 5, 2024",
    
    // Careers page
    "careers.title": "Join Our Team",
    "careers.subtitle": "Help us build the future of lead management and fraud prevention.",
    "careers.why_join.title": "Why Join LeadShield?",
    "careers.why_join.meaningful.title": "Meaningful Work",
    "careers.why_join.meaningful.desc": "Help businesses save time and resources by protecting them from fraudulent leads.",
    "careers.why_join.growth.title": "Growth and Learning",
    "careers.why_join.growth.desc": "We invest in our employees' professional development with ongoing training and education.",
    "careers.why_join.collaboration.title": "Collaborative Environment",
    "careers.why_join.collaboration.desc": "Work with a talented team that values collaboration, innovation, and diverse perspectives.",
    "careers.why_join.benefits.title": "Competitive Benefits",
    "careers.why_join.benefits.desc": "Enjoy competitive salary, health benefits, flexible PTO, and stock options.",
    "careers.open_positions": "Open Positions",
    "careers.apply_button": "Apply",
    "careers.no_position": "Don't see a position that matches your skills?",
    "careers.open_application": "Submit Open Application",
    "careers.culture.title": "Our Culture",
    "careers.culture.description": "At LeadShield, we believe in creating an inclusive environment where everyone feels welcome, valued, and empowered to do their best work. We celebrate diversity and are committed to building a team that represents a variety of backgrounds, perspectives, and skills.",
    "careers.positions.frontend.title": "Senior Frontend Developer",
    "careers.positions.ml.title": "Machine Learning Engineer",
    "careers.positions.csm.title": "Customer Success Manager",
    "careers.positions.marketing.title": "Content Marketing Specialist",
    "careers.departments.engineering": "Engineering",
    "careers.departments.data_science": "Data Science",
    "careers.departments.support": "Customer Support",
    "careers.departments.marketing": "Marketing",
    "careers.locations.sf_remote": "San Francisco, CA (Remote Available)",
    "careers.locations.remote": "Remote",
    "careers.job_types.fulltime": "Full-time",
    
    // Contact page
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions or need assistance? We're here to help.",
    "contact.form.title": "Send us a message",
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.company": "Company",
    "contact.form.subject": "Subject",
    "contact.form.message": "Message",
    "contact.form.send": "Send Message",
    "contact.get_in_touch": "Get in Touch",
    "contact.availability": "Our team is available Monday through Friday, 9am to 5pm PT.",
    "contact.email_us": "Email us",
    "contact.call_us": "Call us",
    "contact.visit_office": "Visit our office",
    "contact.faq.title": "Frequently Asked Questions",
    "contact.faq.response_time.question": "How quickly will I receive a response?",
    "contact.faq.response_time.answer": "We aim to respond to all inquiries within 24 business hours.",
    "contact.faq.demos.question": "Do you offer demos?",
    "contact.faq.demos.answer": "Yes! You can schedule a personalized demo with our team to see LeadShield in action.",
    "contact.faq.pricing.question": "Where can I find pricing information?",
    "contact.faq.pricing.answer": "Visit our pricing page or contact our sales team for detailed pricing information."
  },
  pt: {
    // Common
    "app.name": "LeadShield",
    "app.tagline": "Proteja seu Negócio de Leads Fraudulentos",
    // Navigation
    "nav.dashboard": "Painel",
    "nav.leads": "Leads",
    "nav.features": "Recursos",
    "nav.billing": "Cobrança",
    "nav.settings": "Configurações",
    "nav.about": "Sobre",
    "nav.blog": "Blog",
    "nav.careers": "Carreiras",
    "nav.contact": "Contato",
    "nav.success_stories": "Histórias de Sucesso",
    "nav.login": "Entrar",
    "nav.signup": "Cadastre-se Grátis",
    "nav.logout": "Sair",
    // Settings
    "settings.title": "Configurações",
    "settings.subtitle": "Gerencie suas configurações e preferências de conta",
    "settings.account": "Conta",
    "settings.scoreConfig": "Configuração de Pontuação",
    "settings.notifications": "Notificações",
    "settings.api": "Chaves API",
    "settings.score.threshold": "Limite",
    "settings.score.rules": "Regras de Pontuação",
    "settings.score.addRule": "Adicionar Regra",
    "settings.score.editRule": "Editar Regra",
    "settings.score.ruleName": "Nome da Regra",
    "settings.score.ruleDesc": "Descrição",
    "settings.score.saveConfig": "Salvar Configuração",
    "settings.score.weight": "Peso",
    // Homepage
    "home.hero.subtitle": "LeadShield usa pontuação baseada em IA para identificar e bloquear leads suspeitos antes que eles desperdicem seu tempo e recursos.",
    "home.hero.cta.learn": "Saiba Mais",
    "home.hero.benefits.nocredit": "Sem necessidade de cartão de crédito",
    "home.hero.benefits.cancel": "Cancele quando quiser",
    "home.hero.dashboard": "Painel LeadShield",
    "home.hero.realtime": "Proteção em tempo real",
    "home.features.subtitle": "Tudo o que você precisa para proteger seu negócio de leads fraudulentos",
    "home.features.scoring.title": "Pontuação Inteligente",
    "home.features.scoring.desc": "Nosso algoritmo baseado em IA analisa múltiplos pontos de dados para atribuir uma pontuação de risco a cada lead.",
    "home.features.rules.title": "Regras Personalizadas",
    "home.features.rules.desc": "Crie e personalize regras de pontuação com base nas necessidades e requisitos exclusivos do seu negócio.",
    "home.features.team.title": "Colaboração em Equipe",
    "home.features.team.desc": "Adicione membros da equipe com diferentes funções e permissões para gerenciar leads coletivamente.",
    "home.features.billing.title": "Cobrança Flexível",
    "home.features.billing.desc": "Escolha entre cobrança mensal e anual com planos que crescem conforme seu negócio.",
    "home.features.protection.title": "Proteção em Tempo Real",
    "home.features.protection.desc": "Identifique e bloqueie leads suspeitos em tempo real antes que entrem no seu funil de vendas.",
    "home.features.api.title": "Integração API",
    "home.features.api.desc": "Integre perfeitamente com seu CRM existente, ferramentas de marketing e outros sistemas de software.",
    "home.about.subtitle": "A história por trás do LeadShield",
    "home.about.name": "Fernando Ramalho",
    "home.about.quote": "\"Fundei o LeadShield após experimentar a frustração do tempo e recursos desperdiçados com leads fraudulentos em meu negócio anterior. Eu sabia que deveria haver uma maneira melhor de proteger as empresas desse problema comum.\"",
    "home.about.bio1": "Com mais de 8 anos de experiência em marketing e geração de leads, Fernando identificou uma lacuna crítica no mercado: a falta de ferramentas robustas para detectar e prevenir leads fraudulentos antes que desperdicem tempo e recursos valiosos.",
    "home.about.bio2": "Desde o lançamento do LeadShield, Fernando liderou a empresa na proteção de milhares de negócios em todo o mundo, ajudando-os a economizar tempo, dinheiro e focar em oportunidades genuínas de crescimento.",
    "home.about.role": "Fernando Ramalho, Fundador & CEO",
    "home.about.cta": "Saiba Mais Sobre Nós",
    "home.pricing.subtitle": "Escolha o plano perfeito para as necessidades do seu negócio",
    "home.pricing.free.name": "Gratuito",
    "home.pricing.free.desc": "Comece com proteção básica de leads",
    "home.pricing.free.feature1": "Até 100 leads/mês",
    "home.pricing.free.feature2": "Pontuação básica de leads", 
    "home.pricing.free.feature3": "Suporte por e-mail",
    "home.pricing.start.name": "Inicial",
    "home.pricing.start.desc": "Proteção para negócios em crescimento",
    "home.pricing.start.feature1": "Até 500 leads/mês",
    "home.pricing.start.feature2": "Regras personalizadas (2)",
    "home.pricing.start.feature3": "Membros da equipe (2)",
    "home.pricing.growth.tag": "Mais Popular",
    "home.pricing.growth.name": "Crescimento",
    "home.pricing.growth.desc": "Proteção avançada e análises",
    "home.pricing.growth.feature1": "Até 2.000 leads/mês",
    "home.pricing.growth.feature2": "Regras personalizadas (5)",
    "home.pricing.growth.feature3": "Membros da equipe (5)",
    "home.pricing.growth.feature4": "Análises avançadas",
    "home.pricing.full.name": "Proteção Total",
    "home.pricing.full.desc": "Proteção nível empresarial",
    "home.pricing.full.feature1": "Leads ilimitados",
    "home.pricing.full.feature2": "Regras personalizadas ilimitadas",
    "home.pricing.full.feature3": "Membros da equipe ilimitados",
    "home.pricing.full.feature4": "Suporte prioritário 24/7",
    "home.pricing.cta": "Começar",
    "home.cta.title": "Pronto para proteger seu negócio?",
    "home.cta.subtitle": "Comece a usar o LeadShield hoje e pare de desperdiçar tempo e recursos com leads fraudulentos.",
    "footer.resources": "Recursos",
    "footer.docs": "Documentação",
    "footer.support": "Suporte",
    "footer.privacy": "Privacidade",
    "footer.terms": "Termos",
    "footer.company": "Empresa",
    "footer.copyright": "Todos os direitos reservados.",
    
    // Login page
    "login.welcome": "Bem-vindo de volta",
    "login.enter_credentials": "Insira suas credenciais para acessar sua conta",
    "login.email": "Email",
    "login.email_placeholder": "voce@exemplo.com",
    "login.password": "Senha",
    "login.password_placeholder": "••••••••",
    "login.logging_in": "Entrando...",
    "login.demo_credentials": "Credenciais de demonstração:",
    "login.forgot_password": "Esqueceu a senha?",
    
    // Signup page
    "signup.create_account": "Criar conta",
    "signup.enter_details": "Insira seus dados para criar uma nova conta",
    "signup.full_name": "Nome Completo",
    "signup.name_placeholder": "João Silva",
    "signup.company_name": "Nome da Empresa",
    "signup.company_placeholder": "Sua Empresa",
    "signup.creating_account": "Criando conta...",
    "signup.create_button": "Criar Conta",
    
    // About page
    "about.title": "Sobre o LeadShield",
    "about.subtitle": "Estamos em uma missão para ajudar empresas a se protegerem de leads fraudulentos e focar em oportunidades genuínas.",
    "about.story.title": "Nossa História",
    "about.story.paragraph1": "O LeadShield foi fundado em 2023 depois que nosso fundador experimentou em primeira mão a frustração de lidar com leads falsos que desperdiçavam tempo e recursos.",
    "about.story.paragraph2": "O que começou como uma ferramenta interna rapidamente evoluiu para uma plataforma abrangente que ajuda empresas de todos os tamanhos a identificar e filtrar leads fraudulentos antes que entrem no funil de vendas.",
    "about.story.paragraph3": "Hoje, o LeadShield protege milhares de empresas em todo o mundo, economizando inúmeras horas e recursos que seriam desperdiçados com leads falsos.",
    "about.story.office": "Nossa sede em São Francisco, CA",
    "about.mission.title": "Nossa Missão",
    "about.mission.statement": "Capacitar empresas com ferramentas inteligentes que as protejam de fraudes e permitam que se concentrem em oportunidades genuínas de crescimento.",
    "about.mission.attribution": "Declaração de Missão do LeadShield",
    "about.values.title": "Nossos Valores",
    "about.values.protection.title": "Proteção",
    "about.values.protection.desc": "Acreditamos na criação de sistemas robustos que protejam as empresas de potenciais ameaças e vulnerabilidades.",
    "about.values.trust.title": "Confiança",
    "about.values.trust.desc": "Construímos relacionamentos baseados em transparência, confiabilidade e entrega consistente de serviços de qualidade.",
    "about.values.innovation.title": "Inovação",
    "about.values.innovation.desc": "Evoluímos continuamente nossa tecnologia para ficarmos à frente de ameaças emergentes e fornecer soluções de ponta.",
    
    // Blog page
    "blog.title": "Blog LeadShield",
    "blog.subtitle": "Insights e estratégias para proteger seu negócio de leads fraudulentos",
    "blog.by": "Por",
    "blog.read_more": "Leia Mais",
    "blog.categories.lead_management": "Gestão de Leads",
    "blog.categories.business": "Negócios",
    "blog.categories.technology": "Tecnologia",
    "blog.categories.news": "Notícias da Empresa",
    "blog.categories.lead_generation": "Geração de Leads",
    "blog.team": "Equipe LeadShield",
    "blog.post1.title": "Como Identificar Leads Fraudulentos: 5 Sinais de Alerta",
    "blog.post1.excerpt": "Aprenda a identificar leads falsos antes que eles desperdicem seu tempo e recursos.",
    "blog.post1.date": "10 de Maio de 2024",
    "blog.post2.title": "O Verdadeiro Custo dos Leads Falsos para Pequenas Empresas",
    "blog.post2.excerpt": "Descubra como leads fraudulentos impactam seu resultado final e o que você pode fazer a respeito.",
    "blog.post2.date": "25 de Abril de 2024",
    "blog.post3.title": "Verificação de Leads com IA: O Futuro das Vendas",
    "blog.post3.excerpt": "Veja como a inteligência artificial está revolucionando a forma como as empresas validam leads.",
    "blog.post3.date": "12 de Abril de 2024",
    "blog.post4.title": "LeadShield Anuncia Financiamento Série A",
    "blog.post4.excerpt": "Estamos entusiasmados em anunciar nossa mais recente rodada de financiamento, que nos ajudará a expandir nosso alcance e continuar inovando.",
    "blog.post4.date": "20 de Março de 2024",
    "blog.post5.title": "Top 10 Estratégias de Geração de Leads para 2024",
    "blog.post5.excerpt": "Mantenha-se à frente com estas técnicas comprovadas de geração de leads.",
    "blog.post5.date": "5 de Fevereiro de 2024",
    
    // Careers page
    "careers.title": "Junte-se à Nossa Equipe",
    "careers.subtitle": "Ajude-nos a construir o futuro da gestão de leads e prevenção de fraudes.",
    "careers.why_join.title": "Por Que Se Juntar ao LeadShield?",
    "careers.why_join.meaningful.title": "Trabalho Significativo",
    "careers.why_join.meaningful.desc": "Ajude empresas a economizar tempo e recursos, protegendo-as de leads fraudulentos.",
    "careers.why_join.growth.title": "Crescimento e Aprendizado",
    "careers.why_join.growth.desc": "Investimos no desenvolvimento profissional de nossos funcionários com treinamento e educação contínuos.",
    "careers.why_join.collaboration.title": "Ambiente Colaborativo",
    "careers.why_join.collaboration.desc": "Trabalhe com uma equipe talentosa que valoriza colaboração, inovação e perspectivas diversas.",
    "careers.why_join.benefits.title": "Benefícios Competitivos",
    "careers.why_join.benefits.desc": "Desfrute de salário competitivo, benefícios de saúde, PTO flexível e opções de ações.",
    "careers.open_positions": "Vagas Abertas",
    "careers.apply_button": "Candidatar-se",
    "careers.no_position": "Não vê uma posição que corresponda às suas habilidades?",
    "careers.open_application": "Enviar Aplicação Aberta",
    "careers.culture.title": "Nossa Cultura",
    "careers.culture.description": "No LeadShield, acreditamos em criar um ambiente inclusivo onde todos se sintam bem-vindos, valorizados e capacitados para fazer seu melhor trabalho. Celebramos a diversidade e estamos comprometidos em construir uma equipe que represente uma variedade de origens, perspectivas e habilidades.",
    "careers.positions.frontend.title": "Desenvolvedor Frontend Sênior",
    "careers.positions.ml.title": "Engenheiro de Aprendizado de Máquina",
    "careers.positions.csm.title": "Gerente de Sucesso do Cliente",
    "careers.positions.marketing.title": "Especialista em Marketing de Conteúdo",
    "careers.departments.engineering": "Engenharia",
    "careers.departments.data_science": "Ciência de Dados",
    "careers.departments.support": "Suporte ao Cliente",
    "careers.departments.marketing": "Marketing",
    "careers.locations.sf_remote": "São Francisco, CA (Remoto Disponível)",
    "careers.locations.remote": "Remoto",
    "careers.job_types.fulltime": "Tempo Integral",
    
    // Contact page
    "contact.title": "Entre em Contato",
    "contact.subtitle": "Tem perguntas ou precisa de assistência? Estamos aqui para ajudar.",
    "contact.form.title": "Envie-nos uma mensagem",
    "contact.form.name": "Nome",
    "contact.form.email": "Email",
    "contact.form.company": "Empresa",
    "contact.form.subject": "Assunto",
    "contact.form.message": "Mensagem",
    "contact.form.send": "Enviar Mensagem",
    "contact.get_in_touch": "Entre em Contato",
    "contact.availability": "Nossa equipe está disponível de segunda a sexta, das 9h às 17h PT.",
    "contact.email_us": "Envie-nos um email",
    "contact.call_us": "Ligue para nós",
    "contact.visit_office": "Visite nosso escritório",
    "contact.faq.title": "Perguntas Frequentes",
    "contact.faq.response_time.question": "Quão rápido receberei uma resposta?",
    "contact.faq.response_time.answer": "Nosso objetivo é responder a todas as consultas dentro de 24 horas úteis.",
    "contact.faq.demos.question": "Vocês oferecem demonstrações?",
    "contact.faq.demos.answer": "Sim! Você pode agendar uma demonstração personalizada com nossa equipe para ver o LeadShield em ação.",
    "contact.faq.pricing.question": "Onde posso encontrar informações sobre preços?",
    "contact.faq.pricing.answer": "Visite nossa página de preços ou entre em contato com nossa equipe de vendas para informações detalhadas sobre preços."
  },
  es: {
    // Common
    "app.name": "LeadShield",
    "app.tagline": "Proteja su Negocio de Leads Fraudulentos",
    // Navigation
    "nav.dashboard": "Panel",
    "nav.leads": "Leads",
    "nav.features": "Características",
    "nav.billing": "Facturación",
    "nav.settings": "Configuración",
    "nav.about": "Acerca de",
    "nav.blog": "Blog",
    "nav.careers": "Carreras",
    "nav.contact": "Contacto",
    "nav.success_stories": "Casos de Éxito",
    "nav.login": "Iniciar Sesión",
    "nav.signup": "Registrarse Gratis",
    "nav.logout": "Cerrar Sesión",
    // Settings
    "settings.title": "Configuración",
    "settings.subtitle": "Administre su configuración y preferencias de cuenta",
    "settings.account": "Cuenta",
    "settings.scoreConfig": "Configuración de Puntuación",
    "settings.notifications": "Notificaciones",
    "settings.api": "Claves API",
    "settings.score.threshold": "Umbral",
    "settings.score.rules": "Reglas de Puntuación",
    "settings.score.addRule": "Añadir Regla",
    "settings.score.editRule": "Editar Regla",
    "settings.score.ruleName": "Nombre de Regla",
    "settings.score.ruleDesc": "Descripción",
    "settings.score.saveConfig": "Guardar Configuración",
    "settings.score.weight": "Peso",
    // Homepage
    "home.hero.subtitle": "LeadShield utiliza puntuación basada en IA para identificar y bloquear leads sospechosos antes de que desperdicien su tiempo y recursos.",
    "home.hero.cta.learn": "Saber Más",
    "home.hero.benefits.nocredit": "No se requiere tarjeta de crédito",
    "home.hero.benefits.cancel": "Cancele cuando quiera",
    "home.hero.dashboard": "Panel de LeadShield",
    "home.hero.realtime": "Protección en tiempo real",
    "home.features.subtitle": "Todo lo que necesita para proteger su negocio de leads fraudulentos",
    "home.features.scoring.title": "Puntuación Inteligente",
    "home.features.scoring.desc": "Nuestro algoritmo basado en IA analiza múltiples puntos de datos para asignar una puntuación de riesgo a cada lead.",
    "home.features.rules.title": "Reglas Personalizadas",
    "home.features.rules.desc": "Cree y personalice reglas de puntuación basadas en las necesidades y requisitos únicos de su negocio.",
    "home.features.team.title": "Colaboración en Equipo",
    "home.features.team.desc": "Añada miembros del equipo con diferentes roles y permisos para gestionar leads colectivamente.",
    "home.features.billing.title": "Facturación Flexible",
    "home.features.billing.desc": "Elija entre facturación mensual y anual con planes que escalan a medida que su negocio crece.",
    "home.features.protection.title": "Protección en Tiempo Real",
    "home.features.protection.desc": "Identifique y bloquee leads sospechosos en tiempo real antes de que entren en su embudo de ventas.",
    "home.features.api.title": "Integración API",
    "home.features.api.desc": "Intégrese perfectamente con su CRM existente, herramientas de marketing y otros sistemas de software.",
    "home.about.subtitle": "La historia detrás de LeadShield",
    "home.about.name": "Fernando Ramalho",
    "home.about.quote": "\"Fundé LeadShield después de experimentar la frustración del tiempo y recursos desperdiciados en leads fraudulentos en mi negocio anterior. Sabía que debía haber una mejor manera de proteger a las empresas de este problema común.\"",
    "home.about.bio1": "Con más de 8 años de experiencia en marketing y generación de leads, Fernando identificó una brecha crítica en el mercado: la falta de herramientas robustas para detectar y prevenir leads fraudulentos antes de que desperdicien tiempo y recursos valiosos.",
    "home.about.bio2": "Desde el lanzamiento de LeadShield, Fernando ha liderado la compañía en la protección de miles de negocios alrededor del mundo, ayudándoles a ahorrar tiempo, dinero y enfocarse en oportunidades genuinas de crecimiento.",
    "home.about.role": "Fernando Ramalho, Fundador & CEO",
    "home.about.cta": "Conozca Más Sobre Nosotros",
    "home.pricing.subtitle": "Elija el plan perfecto para las necesidades de su negocio",
    "home.pricing.free.name": "Gratis",
    "home.pricing.free.desc": "Comience con protección básica de leads",
    "home.pricing.free.feature1": "Hasta 100 leads/mes",
    "home.pricing.free.feature2": "Puntuación básica de leads", 
    "home.pricing.free.feature3": "Soporte por correo electrónico",
    "home.pricing.start.name": "Inicio",
    "home.pricing.start.desc": "Protección para negocios en crecimiento",
    "home.pricing.start.feature1": "Hasta 500 leads/mes",
    "home.pricing.start.feature2": "Reglas personalizadas (2)",
    "home.pricing.start.feature3": "Miembros del equipo (2)",
    "home.pricing.growth.tag": "Más Popular",
    "home.pricing.growth.name": "Crecimiento",
    "home.pricing.growth.desc": "Protección avanzada y análisis",
    "home.pricing.growth.feature1": "Hasta 2.000 leads/mes",
    "home.pricing.growth.feature2": "Reglas personalizadas (5)",
    "home.pricing.growth.feature3": "Miembros del equipo (5)",
    "home.pricing.growth.feature4": "Análisis avanzados",
    "home.pricing.full.name": "Protección Total",
    "home.pricing.full.desc": "Protección a nivel empresarial",
    "home.pricing.full.feature1": "Leads ilimitados",
    "home.pricing.full.feature2": "Reglas personalizadas ilimitadas",
    "home.pricing.full.feature3": "Miembros del equipo ilimitados",
    "home.pricing.full.feature4": "Soporte prioritario 24/7",
    "home.pricing.cta": "Comenzar",
    "home.cta.title": "¿Listo para proteger su negocio?",
    "home.cta.subtitle": "Comience a usar LeadShield hoy y deje de perder tiempo y recursos en leads fraudulentos.",
    "footer.resources": "Recursos",
    "footer.docs": "Documentación",
    "footer.support": "Soporte",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.company": "Empresa",
    "footer.copyright": "Todos los derechos reservados.",
    
    // Login page
    "login.welcome": "Bienvenido de nuevo",
    "login.enter_credentials": "Introduzca sus credenciales para acceder a su cuenta",
    "login.email": "Email",
    "login.email_placeholder": "tu@ejemplo.com",
    "login.password": "Contraseña",
    "login.password_placeholder": "••••••••",
    "login.logging_in": "Iniciando sesión...",
    "login.demo_credentials": "Credenciales de demostración:",
    "login.forgot_password": "¿Olvidó su contraseña?",
    
    // Signup page
    "signup.create_account": "Crear cuenta",
    "signup.enter_details": "Introduzca sus datos para crear una nueva cuenta",
    "signup.full_name": "Nombre Completo",
    "signup.name_placeholder": "Juan Pérez",
    "signup.company_name": "Nombre de la Empresa",
    "signup.company_placeholder": "Su Empresa",
    "signup.creating_account": "Creando cuenta...",
    "signup.create_button": "Crear Cuenta",
    
    // About page
    "about.title": "Acerca de LeadShield",
    "about.subtitle": "Estamos en una misión para ayudar a las empresas a protegerse de leads fraudulentos y enfocarse en oportunidades genuinas.",
    "about.story.title": "Nuestra Historia",
    "about.story.paragraph1": "LeadShield fue fundado en 2023 después de que nuestro fundador experimentara de primera mano la frustración de lidiar con leads falsos que desperdiciaban tiempo y recursos.",
    "about.story.paragraph2": "Lo que comenzó como una herramienta interna rápidamente evolucionó a una plataforma integral que ayuda a empresas de todos los tamaños a identificar y filtrar leads fraudulentos antes de que entren al embudo de ventas.",
    "about.story.paragraph3": "Hoy, LeadShield protege a miles de empresas en todo el mundo, ahorrándoles innumerables horas y recursos que de otro modo se desperdiciarían en leads falsos.",
    "about.story.office": "Nuestras oficinas centrales en San Francisco, CA",
    "about.mission.title": "Nuestra Misión",
    "about.mission.statement": "Empoderar a las empresas con herramientas inteligentes que las protejan del fraude y les permitan enfocarse en oportunidades genuinas de crecimiento.",
    "about.mission.attribution": "Declaración de Misión de LeadShield",
    "about.values.title": "Nuestros Valores",
    "about.values.protection.title": "Protección",
    "about.values.protection.desc": "Creemos en crear sistemas robustos que protejan a las empresas de amenazas y vulnerabilidades potenciales.",
    "about.values.trust.title": "Confianza",
    "about.values.trust.desc": "Construimos relaciones basadas en la transparencia, la fiabilidad y la entrega constante de servicios de calidad.",
    "about.values.innovation.title": "Innovación",
    "about.values.innovation.desc": "Evolucionamos continuamente nuestra tecnología para mantenernos por delante de amenazas emergentes y proporcionar soluciones de vanguardia.",
    
    // Blog page
    "blog.title": "Blog de LeadShield",
    "blog.subtitle": "Conocimientos y estrategias para proteger su negocio de leads fraudulentos",
    "blog.by": "Por",
    "blog.read_more": "Leer Más",
    "blog.categories.lead_management": "Gestión de Leads",
    "blog.categories.business": "Negocios",
    "blog.categories.technology": "Tecnología",
    "blog.categories.news": "Noticias de la Empresa",
    "blog.categories.lead_generation": "Generación de Leads",
    "blog.team": "Equipo de LeadShield",
    "blog.post1.title": "Cómo Identificar Leads Fraudulentos: 5 Señales de Advertencia",
    "blog.post1.excerpt": "Aprenda a detectar leads falsos antes de que desperdicien su tiempo y recursos.",
    "blog.post1.date": "10 de Mayo de 2024",
    "blog.post2.title": "El Verdadero Costo de los Leads Falsos para Pequeñas Empresas",
    "blog.post2.excerpt": "Descubra cómo los leads fraudulentos impactan su resultado final y qué puede hacer al respecto.",
    "blog.post2.date": "25 de Abril de 2024",
    "blog.post3.title": "Verificación de Leads con IA: El Futuro de las Ventas",
    "blog.post3.excerpt": "Vea cómo la inteligencia artificial está revolucionando la forma en que las empresas validan leads.",
    "blog.post3.date": "12 de Abril de 2024",
    "blog.post4.title": "LeadShield Anuncia Financiación Serie A",
    "blog.post4.excerpt": "Estamos emocionados de anunciar nuestra última ronda de financiación, que nos ayudará a expandir nuestro alcance y seguir innovando.",
    "blog.post4.date": "20 de Marzo de 2024",
    "blog.post5.title": "Las 10 Mejores Estrategias de Generación de Leads para 2024",
    "blog.post5.excerpt": "Manténgase a la vanguardia con estas técnicas probadas de generación de leads.",
    "blog.post5.date": "5 de Febrero de 2024",
    
    // Careers page
    "careers.title": "Únase a Nuestro Equipo",
    "careers.subtitle": "Ayúdenos a construir el futuro de la gestión de leads y la prevención de fraudes.",
    "careers.why_join.title": "¿Por Qué Unirse a LeadShield?",
    "careers.why_join.meaningful.title": "Trabajo Significativo",
    "careers.why_join.meaningful.desc": "Ayude a las empresas a ahorrar tiempo y recursos protegiéndolas de leads fraudulentos.",
    "careers.why_join.growth.title": "Crecimiento y Aprendizaje",
    "careers.why_join.growth.desc": "Invertimos en el desarrollo profesional de nuestros empleados con formación y educación continuas.",
    "careers.why_join.collaboration.title": "Entorno Colaborativo",
    "careers.why_join.collaboration.desc": "Trabaje con un equipo talentoso que valora la colaboración, la innovación y las perspectivas diversas.",
    "careers.why_join.benefits.title": "Beneficios Competitivos",
    "careers.why_join.benefits.desc": "Disfrute de salario competitivo, beneficios de salud, tiempo libre pagado flexible y opciones de acciones.",
    "careers.open_positions": "Posiciones Abiertas",
    "careers.apply_button": "Aplicar",
    "careers.no_position": "¿No ve una posición que coincida con sus habilidades?",
    "careers.open_application": "Enviar Solicitud Abierta",
    "careers.culture.title": "Nuestra Cultura",
    "careers.culture.description": "En LeadShield, creemos en crear un entorno inclusivo donde todos se sientan bienvenidos, valorados y capacitados para hacer su mejor trabajo. Celebramos la diversidad y estamos comprometidos a construir un equipo que represente una variedad de antecedentes, perspectivas y habilidades.",
    "careers.positions.frontend.title": "Desarrollador Frontend Senior",
    "careers.positions.ml.title": "Ingeniero de Aprendizaje Automático",
    "careers.positions.csm.title": "Gerente de Éxito del Cliente",
    "careers.positions.marketing.title": "Especialista en Marketing de Contenidos",
    "careers.departments.engineering": "Ingeniería",
    "careers.departments.data_science": "Ciencia de Datos",
    "careers.departments.support": "Soporte al Cliente",
    "careers.departments.marketing": "Marketing",
    "careers.locations.sf_remote": "San Francisco, CA (Remoto Disponible)",
    "careers.locations.remote": "Remoto",
    "careers.job_types.fulltime": "Tiempo Completo",
    
    // Contact page
    "contact.title": "Contáctenos",
    "contact.subtitle": "¿Tiene preguntas o necesita ayuda? Estamos aquí para ayudarle.",
    "contact.form.title": "Envíenos un mensaje",
    "contact.form.name": "Nombre",
    "contact.form.email": "Email",
    "contact.form.company": "Empresa",
    "contact.form.subject": "Asunto",
    "contact.form.message": "Mensaje",
    "contact.form.send": "Enviar Mensaje",
    "contact.get_in_touch": "Póngase en Contacto",
    "contact.availability": "Nuestro equipo está disponible de lunes a viernes, de 9 a.m. a 5 p.m. PT.",
    "contact.email_us": "Envíenos un email",
    "contact.call_us": "Llámenos",
    "contact.visit_office": "Visite nuestra oficina",
    "contact.faq.title": "Preguntas Frecuentes",
    "contact.faq.response_time.question": "¿Qué tan rápido recibiré una respuesta?",
    "contact.faq.response_time.answer": "Nuestro objetivo es responder a todas las consultas dentro de las 24 horas hábiles.",
    "contact.faq.demos.question": "¿Ofrecen demostraciones?",
    "contact.faq.demos.answer": "¡Sí! Puede programar una demostración personalizada con nuestro equipo para ver LeadShield en acción.",
    "contact.faq.pricing.question": "¿Dónde puedo encontrar información de precios?",
    "contact.faq.pricing.answer": "Visite nuestra página de precios o contacte a nuestro equipo de ventas para información detallada de precios."
  },
  fr: {
    // Common
    "app.name": "LeadShield",
    "app.tagline": "Protégez Votre Entreprise Contre les Leads Frauduleux",
    // Navigation
    "nav.dashboard": "Tableau de Bord",
    "nav.leads": "Leads",
    "nav.features": "Fonctionnalités",
    "nav.billing": "Facturation",
    "nav.settings": "Paramètres",
    "nav.about": "À Propos",
    "nav.blog": "Blog",
    "nav.careers": "Carrières",
    "nav.contact": "Contact",
    "nav.success_stories": "Témoignages",
    "nav.login": "Connexion",
    "nav.signup": "Inscription Gratuite",
    "nav.logout": "Déconnexion",
    // Settings
    "settings.title": "Paramètres",
    "settings.subtitle": "Gérez vos paramètres et préférences de compte",
    "settings.account": "Compte",
    "settings.scoreConfig": "Configuration de Score",
    "settings.notifications": "Notifications",
    "settings.api": "Clés API",
    "settings.score.threshold": "Seuil",
    "settings.score.rules": "Règles de Scoring",
    "settings.score.addRule": "Ajouter une Règle",
    "settings.score.editRule": "Modifier la Règle",
    "settings.score.ruleName": "Nom de la Règle",
    "settings.score.ruleDesc": "Description",
    "settings.score.saveConfig": "Enregistrer la Configuration",
    "settings.score.weight": "Poids",
    // Homepage
    "home.hero.subtitle": "LeadShield utilise un scoring basé sur l'IA pour identifier et bloquer les leads suspects avant qu'ils ne gaspillent votre temps et vos ressources.",
    "home.hero.cta.learn": "En Savoir Plus",
    "home.hero.benefits.nocredit": "Pas de carte de crédit requise",
    "home.hero.benefits.cancel": "Annulez quand vous voulez",
    "home.hero.dashboard": "Tableau de bord LeadShield",
    "home.hero.realtime": "Protection en temps réel",
    "home.features.subtitle": "Tout ce dont vous avez besoin pour protéger votre entreprise des leads frauduleux",
    "home.features.scoring.title": "Scoring Intelligent",
    "home.features.scoring.desc": "Notre algorithme basé sur l'IA analyse de multiples points de données pour attribuer un score de risque à chaque lead.",
    "home.features.rules.title": "Règles Personnalisées",
    "home.features.rules.desc": "Créez et personnalisez des règles de scoring en fonction des besoins et exigences uniques de votre entreprise.",
    "home.features.team.title": "Collaboration d'Équipe",
    "home.features.team.desc": "Ajoutez des membres d'équipe avec différents rôles et permissions pour gérer collectivement les leads.",
    "home.features.billing.title": "Facturation Flexible",
    "home.features.billing.desc": "Choisissez entre facturation mensuelle et annuelle avec des plans qui évoluent avec votre entreprise.",
    "home.features.protection.title": "Protection en Temps Réel",
    "home.features.protection.desc": "Identifiez et bloquez les leads suspects en temps réel avant qu'ils n'entrent dans votre entonnoir de vente.",
    "home.features.api.title": "Intégration API",
    "home.features.api.desc": "Intégrez-vous parfaitement avec votre CRM existant, vos outils marketing et autres systèmes logiciels.",
    "home.about.subtitle": "L'histoire derrière LeadShield",
    "home.about.name": "Fernando Ramalho",
    "home.about.quote": "\"J'ai fondé LeadShield après avoir vécu la frustration du temps et des ressources gaspillés sur des leads frauduleux dans mon entreprise précédente. Je savais qu'il devait y avoir une meilleure façon de protéger les entreprises de ce problème courant.\"",
    "home.about.bio1": "Avec plus de 8 ans d'expérience en marketing et génération de leads, Fernando a identifié une lacune critique sur le marché : l'absence d'outils robustes pour détecter et prévenir les leads frauduleux avant qu'ils ne gaspillent du temps et des ressources précieux.",
    "home.about.bio2": "Depuis le lancement de LeadShield, Fernando a dirigé l'entreprise dans la protection de milliers d'entreprises à travers le monde, les aidant à économiser du temps, de l'argent et à se concentrer sur de véritables opportunités de croissance.",
    "home.about.role": "Fernando Ramalho, Fondateur & PDG",
    "home.about.cta": "En Savoir Plus Sur Nous",
    "home.pricing.subtitle": "Choisissez le plan parfait pour les besoins de votre entreprise",
    "home.pricing.free.name": "Gratuit",
    "home.pricing.free.desc": "Commencez avec une protection de base des leads",
    "home.pricing.free.feature1": "Jusqu'à 100 leads/mois",
    "home.pricing.free.feature2": "Scoring de base des leads", 
    "home.pricing.free.feature3": "Support par email",
    "home.pricing.start.name": "Démarrage",
    "home.pricing.start.desc": "Protection pour entreprises en croissance",
    "home.pricing.start.feature1": "Jusqu'à 500 leads/mois",
    "home.pricing.start.feature2": "Règles personnalisées (2)",
    "home.pricing.start.feature3": "Membres d'équipe (2)",
    "home.pricing.growth.tag": "Le Plus Populaire",
    "home.pricing.growth.name": "Croissance",
    "home.pricing.growth.desc": "Protection avancée et analyses",
    "home.pricing.growth.feature1": "Jusqu'à 2 000 leads/mois",
    "home.pricing.growth.feature2": "Règles personnalisées (5)",
    "home.pricing.growth.feature3": "Membres d'équipe (5)",
    "home.pricing.growth.feature4": "Analyses avancées",
    "home.pricing.full.name": "Protection Complète",
    "home.pricing.full.desc": "Protection niveau entreprise",
    "home.pricing.full.feature1": "Leads illimités",
    "home.pricing.full.feature2": "Règles personnalisées illimitées",
    "home.pricing.full.feature3": "Membres d'équipe illimités",
    "home.pricing.full.feature4": "Support prioritaire 24/7",
    "home.pricing.cta": "Commencer",
    "home.cta.title": "Prêt à protéger votre entreprise ?",
    "home.cta.subtitle": "Commencez à utiliser LeadShield aujourd'hui et arrêtez de perdre du temps et des ressources sur des leads frauduleux.",
    "footer.resources": "Ressources",
    "footer.docs": "Documentation",
    "footer.support": "Support",
    "footer.privacy": "Confidentialité",
    "footer.terms": "Conditions",
    "footer.company": "Entreprise",
    "footer.copyright": "Tous droits réservés.",
    
    // Login page
    "login.welcome": "Bienvenue",
    "login.enter_credentials": "Entrez vos identifiants pour accéder à votre compte",
    "login.email": "Email",
    "login.email_placeholder": "vous@exemple.com",
    "login.password": "Mot de passe",
    "login.password_placeholder": "••••••••",
    "login.logging_in": "Connexion en cours...",
    "login.demo_credentials": "Identifiants de démonstration :",
    "login.forgot_password": "Mot de passe oublié ?",
    
    // Signup page
    "signup.create_account": "Créer un compte",
    "signup.enter_details": "Entrez vos informations pour créer un nouveau compte",
    "signup.full_name": "Nom Complet",
    "signup.name_placeholder": "Jean Dupont",
    "signup.company_name": "Nom de l'Entreprise",
    "signup.company_placeholder": "Votre Entreprise",
    "signup.creating_account": "Création du compte...",
    "signup.create_button": "Créer un Compte",
    
    // About page
    "about.title": "À Propos de LeadShield",
    "about.subtitle": "Nous avons pour mission d'aider les entreprises à se protéger des leads frauduleux et à se concentrer sur les opportunités authentiques.",
    "about.story.title": "Notre Histoire",
    "about.story.paragraph1": "LeadShield a été fondé en 2023 après que notre fondateur ait vécu personnellement la frustration de traiter avec des leads frauduleux qui gaspillaient du temps et des ressources.",
    "about.story.paragraph2": "Ce qui a commencé comme un outil interne s'est rapidement transformé en une plateforme complète qui aide les entreprises de toutes tailles à identifier et filtrer les leads frauduleux avant qu'ils n'entrent dans le pipeline de ventes.",
    "about.story.paragraph3": "Aujourd'hui, LeadShield protège des milliers d'entreprises dans le monde entier, leur faisant économiser d'innombrables heures et ressources qui auraient été gaspillées sur des leads frauduleux.",
    "about.story.office": "Notre siège à San Francisco, CA",
    "about.mission.title": "Notre Mission",
    "about.mission.statement": "Doter les entreprises d'outils intelligents qui les protègent contre la fraude et leur permettent de se concentrer sur de véritables opportunités de croissance.",
    "about.mission.attribution": "Énoncé de Mission de LeadShield",
    "about.values.title": "Nos Valeurs",
    "about.values.protection.title": "Protection",
    "about.values.protection.desc": "Nous croyons en la création de systèmes robustes qui protègent les entreprises contre les menaces et vulnérabilités potentielles.",
    "about.values.trust.title": "Confiance",
    "about.values.trust.desc": "Nous construisons des relations basées sur la transparence, la fiabilité et la prestation constante de services de qualité.",
    "about.values.innovation.title": "Innovation",
    "about.values.innovation.desc": "Nous faisons évoluer continuellement notre technologie pour rester en avance sur les menaces émergentes et fournir des solutions de pointe.",
    
    // Blog page
    "blog.title": "Blog LeadShield",
    "blog.subtitle": "Perspectives et stratégies pour protéger votre entreprise des leads frauduleux",
    "blog.by": "Par",
    "blog.read_more": "Lire Plus",
    "blog.categories.lead_management": "Gestion des Leads",
    "blog.categories.business": "Entreprise",
    "blog.categories.technology": "Technologie",
    "blog.categories.news": "Actualités de l'Entreprise",
    "blog.categories.lead_generation": "Génération de Leads",
    "blog.team": "Équipe LeadShield",
    "blog.post1.title": "Comment Identifier les Leads Frauduleux : 5 Signaux d'Alerte",
    "blog.post1.excerpt": "Apprenez à repérer les leads frauduleux avant qu'ils ne gaspillent votre temps et vos ressources.",
    "blog.post1.date": "10 mai 2024",
    "blog.post2.title": "Le Vrai Coût des Leads Frauduleux pour les Petites Entreprises",
    "blog.post2.excerpt": "Découvrez comment les leads frauduleux impactent votre résultat net et ce que vous pouvez faire à ce sujet.",
    "blog.post2.date": "25 avril 2024",
    "blog.post3.title": "Vérification des Leads par IA : L'Avenir des Ventes",
    "blog.post3.excerpt": "Voyez comment l'intelligence artificielle révolutionne la façon dont les entreprises valident les leads.",
    "blog.post3.date": "12 avril 2024",
    "blog.post4.title": "LeadShield Annonce un Financement de Série A",
    "blog.post4.excerpt": "Nous sommes ravis d'annoncer notre dernière levée de fonds, qui nous aidera à étendre notre portée et à continuer d'innover.",
    "blog.post4.date": "20 mars 2024",
    "blog.post5.title": "Les 10 Meilleures Stratégies de Génération de Leads pour 2024",
    "blog.post5.excerpt": "Restez à la pointe avec ces techniques éprouvées de génération de leads.",
    "blog.post5.date": "5 février 2024",
    
    // Careers page
    "careers.title": "Rejoignez Notre Équipe",
    "careers.subtitle": "Aidez-nous à construire l'avenir de la gestion des leads et de la prévention des fraudes.",
    "careers.why_join.title": "Pourquoi Rejoindre LeadShield ?",
    "careers.why_join.meaningful.title": "Travail Significatif",
    "careers.why_join.meaningful.desc": "Aidez les entreprises à économiser du temps et des ressources en les protégeant des leads frauduleux.",
    "careers.why_join.growth.title": "Croissance et Apprentissage",
    "careers.why_join.growth.desc": "Nous investissons dans le développement professionnel de nos employés avec une formation et une éducation continues.",
    "careers.why_join.collaboration.title": "Environnement Collaboratif",
    "careers.why_join.collaboration.desc": "Travaillez avec une équipe talentueuse qui valorise la collaboration, l'innovation et les perspectives diverses.",
    "careers.why_join.benefits.title": "Avantages Compétitifs",
    "careers.why_join.benefits.desc": "Bénéficiez d'un salaire compétitif, d'avantages sociaux, de congés flexibles et d'options d'actions.",
    "careers.open_positions": "Postes Ouverts",
    "careers.apply_button": "Postuler",
    "careers.no_position": "Vous ne voyez pas de poste correspondant à vos compétences ?",
    "careers.open_application": "Soumettre une Candidature Ouverte",
    "careers.culture.title": "Notre Culture",
    "careers.culture.description": "Chez LeadShield, nous croyons en la création d'un environnement inclusif où chacun se sent bienvenu, valorisé et habilité à donner le meilleur de lui-même. Nous célébrons la diversité et nous nous engageons à construire une équipe qui représente une variété d'origines, de perspectives et de compétences.",
    "careers.positions.frontend.title": "Développeur Frontend Senior",
    "careers.positions.ml.title": "Ingénieur en Machine Learning",
    "careers.positions.csm.title": "Responsable de la Réussite Client",
    "careers.positions.marketing.title": "Spécialiste en Marketing de Contenu",
    "careers.departments.engineering": "Ingénierie",
    "careers.departments.data_science": "Science des Données",
    "careers.departments.support": "Support Client",
    "careers.departments.marketing": "Marketing",
    "careers.locations.sf_remote": "San Francisco, CA (Télétravail Possible)",
    "careers.locations.remote": "Télétravail",
    "careers.job_types.fulltime": "Temps Plein",
    
    // Contact page
    "contact.title": "Contactez-Nous",
    "contact.subtitle": "Vous avez des questions ou besoin d'assistance ? Nous sommes là pour vous aider.",
    "contact.form.title": "Envoyez-nous un message",
    "contact.form.name": "Nom",
    "contact.form.email": "Email",
    "contact.form.company": "Entreprise",
    "contact.form.subject": "Sujet",
    "contact.form.message": "Message",
    "contact.form.send": "Envoyer le Message",
    "contact.get_in_touch": "Prenez Contact",
    "contact.availability": "Notre équipe est disponible du lundi au vendredi, de 9h à 17h PT.",
    "contact.email_us": "Envoyez-nous un email",
    "contact.call_us": "Appelez-nous",
    "contact.visit_office": "Visitez notre bureau",
    "contact.faq.title": "Questions Fréquemment Posées",
    "contact.faq.response_time.question": "Dans quel délai vais-je recevoir une réponse ?",
    "contact.faq.response_time.answer": "Nous nous efforçons de répondre à toutes les demandes dans les 24 heures ouvrables.",
    "contact.faq.demos.question": "Proposez-vous des démonstrations ?",
    "contact.faq.demos.answer": "Oui ! Vous pouvez planifier une démonstration personnalisée avec notre équipe pour voir LeadShield en action.",
    "contact.faq.pricing.question": "Où puis-je trouver des informations sur les tarifs ?",
    "contact.faq.pricing.answer": "Visitez notre page de tarifs ou contactez notre équipe commerciale pour des informations détaillées sur les tarifs."
  },
  de: {
    // Common
    "app.name": "LeadShield",
    "app.tagline": "Schützen Sie Ihr Unternehmen vor betrügerischen Leads",
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.leads": "Leads",
    "nav.features": "Funktionen",
    "nav.billing": "Abrechnung",
    "nav.settings": "Einstellungen",
    "nav.about": "Über uns",
    "nav.blog": "Blog",
    "nav.careers": "Karriere",
    "nav.contact": "Kontakt",
    "nav.success_stories": "Erfolgsgeschichten",
    "nav.login": "Anmelden",
    "nav.signup": "Kostenlos Registrieren",
    "nav.logout": "Abmelden",
    // Settings
    "settings.title": "Einstellungen",
    "settings.subtitle": "Verwalten Sie Ihre Kontoeinstellungen und Präferenzen",
    "settings.account": "Konto",
    "settings.scoreConfig": "Score-Konfiguration",
    "settings.notifications": "Benachrichtigungen",
    "settings.api": "API-Schlüssel",
    "settings.score.threshold": "Schwellenwert",
    "settings.score.rules": "Scoring-Regeln",
    "settings.score.addRule": "Regel hinzufügen",
    "settings.score.editRule": "Regel bearbeiten",
    "settings.score.ruleName": "Regelname",
    "settings.score.ruleDesc": "Beschreibung",
    "settings.score.saveConfig": "Konfiguration speichern",
    "settings.score.weight": "Gewichtung",
    // Homepage
    "home.hero.subtitle": "LeadShield verwendet KI-gestützte Bewertung, um verdächtige Leads zu identifizieren und zu blockieren, bevor sie Ihre Zeit und Ressourcen verschwenden.",
    "home.hero.cta.learn": "Mehr Erfahren",
    "home.hero.benefits.nocredit": "Keine Kreditkarte erforderlich",
    "home.hero.benefits.cancel": "Jederzeit kündbar",
    "home.hero.dashboard": "LeadShield Dashboard",
    "home.hero.realtime": "Echtzeit-Schutz",
    "home.features.subtitle": "Alles, was Sie benötigen, um Ihr Unternehmen vor betrügerischen Leads zu schützen",
    "home.features.scoring.title": "Intelligente Bewertung",
    "home.features.scoring.desc": "Unser KI-gestützter Algorithmus analysiert mehrere Datenpunkte, um jedem Lead eine Risikobewertung zuzuweisen.",
    "home.features.rules.title": "Benutzerdefinierte Regeln",
    "home.features.rules.desc": "Erstellen und passen Sie Bewertungsregeln basierend auf den einzigartigen Bedürfnissen und Anforderungen Ihres Unternehmens an.",
    "home.features.team.title": "Team-Zusammenarbeit",
    "home.features.team.desc": "Fügen Sie Teammitglieder mit verschiedenen Rollen und Berechtigungen hinzu, um Leads gemeinsam zu verwalten.",
    "home.features.billing.title": "Flexible Abrechnung",
    "home.features.billing.desc": "Wählen Sie zwischen monatlicher und jährlicher Abrechnung mit Plänen, die mit Ihrem Unternehmen wachsen.",
    "home.features.protection.title": "Echtzeit-Schutz",
    "home.features.protection.desc": "Identifizieren und blockieren Sie verdächtige Leads in Echtzeit, bevor sie in Ihren Verkaufstrichter gelangen.",
    "home.features.api.title": "API-Integration",
    "home.features.api.desc": "Nahtlose Integration mit Ihrem bestehenden CRM, Marketing-Tools und anderen Softwaresystemen.",
    "home.about.subtitle": "Die Geschichte hinter LeadShield",
    "home.about.name": "Fernando Ramalho",
    "home.about.quote": "\"Ich habe LeadShield gegründet, nachdem ich in meinem vorherigen Unternehmen die Frustration von verschwendeter Zeit und Ressourcen durch betrügerische Leads erlebt habe. Ich wusste, dass es einen besseren Weg geben musste, Unternehmen vor diesem häufigen Problem zu schützen.\"",
    "home.about.bio1": "Mit über 8 Jahren Erfahrung im Marketing und in der Lead-Generierung identifizierte Fernando eine kritische Marktlücke: das Fehlen robuster Tools zur Erkennung und Verhinderung betrügerischer Leads, bevor sie wertvolle Zeit und Ressourcen verschwenden.",
    "home.about.bio2": "Seit der Gründung von LeadShield hat Fernando das Unternehmen beim Schutz tausender Unternehmen weltweit geführt und ihnen geholfen, Zeit und Geld zu sparen und sich auf echte Wachstumschancen zu konzentrieren.",
    "home.about.role": "Fernando Ramalho, Gründer & CEO",
    "home.about.cta": "Mehr Über Uns Erfahren",
    "home.pricing.subtitle": "Wählen Sie den perfekten Plan für die Bedürfnisse Ihres Unternehmens",
    "home.pricing.free.name": "Kostenlos",
    "home.pricing.free.desc": "Starten Sie mit grundlegendem Lead-Schutz",
    "home.pricing.free.feature1": "Bis zu 100 Leads/Monat",
    "home.pricing.free.feature2": "Grundlegende Lead-Bewertung", 
    "home.pricing.free.feature3": "E-Mail-Support",
    "home.pricing.start.name": "Start",
    "home.pricing.start.desc": "Schutz für wachsende Unternehmen",
    "home.pricing.start.feature1": "Bis zu 500 Leads/Monat",
    "home.pricing.start.feature2": "Benutzerdefinierte Regeln (2)",
    "home.pricing.start.feature3": "Teammitglieder (2)",
    "home.pricing.growth.tag": "Am Beliebtesten",
    "home.pricing.growth.name": "Wachstum",
    "home.pricing.growth.desc": "Erweiterter Schutz und Analysen",
    "home.pricing.growth.feature1": "Bis zu 2.000 Leads/Monat",
    "home.pricing.growth.feature2": "Benutzerdefinierte Regeln (5)",
    "home.pricing.growth.feature3": "Teammitglieder (5)",
    "home.pricing.growth.feature4": "Erweiterte Analysen",
    "home.pricing.full.name": "Vollständiger Schutz",
    "home.pricing.full.desc": "Unternehmensfähiger Schutz",
    "home.pricing.full.feature1": "Unbegrenzte Leads",
    "home.pricing.full.feature2": "Unbegrenzte benutzerdefinierte Regeln",
    "home.pricing.full.feature3": "Unbegrenzte Teammitglieder",
    "home.pricing.full.feature4": "Prioritätssupport rund um die Uhr",
    "home.pricing.cta": "Jetzt Starten",
    "home.cta.title": "Bereit, Ihr Unternehmen zu schützen?",
    "home.cta.subtitle": "Beginnen Sie noch heute mit LeadShield und verschwenden Sie keine Zeit und Ressourcen mehr für betrügerische Leads.",
    "footer.resources": "Ressourcen",
    "footer.docs": "Dokumentation",
    "footer.support": "Support",
    "footer.privacy": "Datenschutz",
    "footer.terms": "Nutzungsbedingungen",
    "footer.company": "Unternehmen",
    "footer.copyright": "Alle Rechte vorbehalten.",
    
    // Login page
    "login.welcome": "Willkommen zurück",
    "login.enter_credentials": "Geben Sie Ihre Zugangsdaten ein, um auf Ihr Konto zuzugreifen",
    "login.email": "E-Mail",
    "login.email_placeholder": "sie@beispiel.de",
    "login.password": "Passwort",
    "login.password_placeholder": "••••••••",
    "login.logging_in": "Anmeldung läuft...",
    "login.demo_credentials": "Demo-Zugangsdaten:",
    "login.forgot_password": "Passwort vergessen?",
    
    // Signup page
    "signup.create_account": "Konto erstellen",
    "signup.enter_details": "Geben Sie Ihre Daten ein, um ein neues Konto zu erstellen",
    "signup.full_name": "Vollständiger Name",
    "signup.name_placeholder": "Max Mustermann",
    "signup.company_name": "Firmenname",
    "signup.company_placeholder": "Ihre Firma",
    "signup.creating_account": "Konto wird erstellt...",
    "signup.create_button": "Konto Erstellen",
    
    // About page
    "about.title": "Über LeadShield",
    "about.subtitle": "Wir haben die Mission, Unternehmen zu helfen, sich vor betrügerischen Leads zu schützen und sich auf echte Chancen zu konzentrieren.",
    "about.story.title": "Unsere Geschichte",
    "about.story.paragraph1": "LeadShield wurde 2023 gegründet, nachdem unser Gründer die Frustration über gefälschte Leads, die Zeit und Ressourcen verschwendeten, aus erster Hand erlebte.",
    "about.story.paragraph2": "Was als internes Tool begann, entwickelte sich schnell zu einer umfassenden Plattform, die Unternehmen jeder Größe hilft, betrügerische Leads zu identifizieren und herauszufiltern, bevor sie in den Verkaufstrichter gelangen.",
    "about.story.paragraph3": "Heute schützt LeadShield Tausende von Unternehmen weltweit und spart ihnen unzählige Stunden und Ressourcen, die sonst für gefälschte Leads verschwendet würden.",
    "about.story.office": "Unser Hauptsitz in San Francisco, CA",
    "about.mission.title": "Unsere Mission",
    "about.mission.statement": "Unternehmen mit intelligenten Werkzeugen auszustatten, die sie vor Betrug schützen und es ihnen ermöglichen, sich auf echte Wachstumschancen zu konzentrieren.",
    "about.mission.attribution": "LeadShield Leitbild",
    "about.values.title": "Unsere Werte",
    "about.values.protection.title": "Schutz",
    "about.values.protection.desc": "Wir glauben an die Schaffung robuster Systeme, die Unternehmen vor potenziellen Bedrohungen und Schwachstellen schützen.",
    "about.values.trust.title": "Vertrauen",
    "about.values.trust.desc": "Wir bauen Beziehungen auf, die auf Transparenz, Zuverlässigkeit und konstanter Bereitstellung von Qualitätsservice basieren.",
    "about.values.innovation.title": "Innovation",
    "about.values.innovation.desc": "Wir entwickeln unsere Technologie kontinuierlich weiter, um aufkommenden Bedrohungen voraus zu sein und hochmoderne Lösungen anzubieten.",
    
    // Blog page
    "blog.title": "LeadShield Blog",
    "blog.subtitle": "Einblicke und Strategien zum Schutz Ihres Unternehmens vor betrügerischen Leads",
    "blog.by": "Von",
    "blog.read_more": "Weiterlesen",
    "blog.categories.lead_management": "Lead-Management",
    "blog.categories.business": "Business",
    "blog.categories.technology": "Technologie",
    "blog.categories.news": "Unternehmensnachrichten",
    "blog.categories.lead_generation": "Lead-Generierung",
    "blog.team": "LeadShield Team",
    "blog.post1.title": "Wie man betrügerische Leads erkennt: 5 Warnsignale",
    "blog.post1.excerpt": "Erfahren Sie, wie Sie gefälschte Leads erkennen können, bevor sie Ihre Zeit und Ressourcen verschwenden.",
    "blog.post1.date": "10. Mai 2024",
    "blog.post2.title": "Die wahren Kosten gefälschter Leads für kleine Unternehmen",
    "blog.post2.excerpt": "Entdecken Sie, wie betrügerische Leads Ihr Endergebnis beeinflussen und was Sie dagegen tun können.",
    "blog.post2.date": "25. April 2024",
    "blog.post3.title": "KI-gestützte Lead-Überprüfung: Die Zukunft des Verkaufs",
    "blog.post3.excerpt": "Sehen Sie, wie künstliche Intelligenz die Art und Weise revolutioniert, wie Unternehmen Leads validieren.",
    "blog.post3.date": "12. April 2024",
    "blog.post4.title": "LeadShield kündigt Series-A-Finanzierung an",
    "blog.post4.excerpt": "Wir freuen uns, unsere neueste Finanzierungsrunde bekannt zu geben, die uns helfen wird, unsere Reichweite zu erweitern und weiterhin zu innovieren.",
    "blog.post4.date": "20. März 2024",
    "blog.post5.title": "Top 10 Lead-Generierungsstrategien für 2024",
    "blog.post5.excerpt": "Bleiben Sie mit diesen bewährten Lead-Generierungstechniken auf dem neuesten Stand.",
    "blog.post5.date": "5. Februar 2024",
    
    // Careers page
    "careers.title": "Werden Sie Teil unseres Teams",
    "careers.subtitle": "Helfen Sie uns, die Zukunft des Lead-Managements und der Betrugsprävention zu gestalten.",
    "careers.why_join.title": "Warum zu LeadShield?",
    "careers.why_join.meaningful.title": "Sinnvolle Arbeit",
    "careers.why_join.meaningful.desc": "Helfen Sie Unternehmen, Zeit und Ressourcen zu sparen, indem Sie sie vor betrügerischen Leads schützen.",
    "careers.why_join.growth.title": "Wachstum und Lernen",
    "careers.why_join.growth.desc": "Wir investieren in die berufliche Entwicklung unserer Mitarbeiter mit kontinuierlicher Schulung und Weiterbildung.",
    "careers.why_join.collaboration.title": "Kollaboratives Umfeld",
    "careers.why_join.collaboration.desc": "Arbeiten Sie mit einem talentierten Team, das Zusammenarbeit, Innovation und vielfältige Perspektiven schätzt.",
    "careers.why_join.benefits.title": "Wettbewerbsfähige Leistungen",
    "careers.why_join.benefits.desc": "Genießen Sie wettbewerbsfähiges Gehalt, Gesundheitsleistungen, flexible Urlaubsregelung und Aktienoptionen.",
    "careers.open_positions": "Offene Stellen",
    "careers.apply_button": "Bewerben",
    "careers.no_position": "Keine Position, die zu Ihren Fähigkeiten passt?",
    "careers.open_application": "Offene Bewerbung einreichen",
    "careers.culture.title": "Unsere Kultur",
    "careers.culture.description": "Bei LeadShield glauben wir an die Schaffung einer inklusiven Umgebung, in der sich jeder willkommen, wertgeschätzt und befähigt fühlt, seine beste Arbeit zu leisten. Wir feiern Vielfalt und sind bestrebt, ein Team aufzubauen, das eine Vielzahl von Hintergründen, Perspektiven und Fähigkeiten repräsentiert.",
    "careers.positions.frontend.title": "Senior Frontend-Entwickler",
    "careers.positions.ml.title": "Maschinelles Lernen Ingenieur",
    "careers.positions.csm.title": "Customer Success Manager",
    "careers.positions.marketing.title": "Content-Marketing-Spezialist",
    "careers.departments.engineering": "Entwicklung",
    "careers.departments.data_science": "Datenwissenschaft",
    "careers.departments.support": "Kundensupport",
    "careers.departments.marketing": "Marketing",
    "careers.locations.sf_remote": "San Francisco, CA (Remote möglich)",
    "careers.locations.remote": "Remote",
    "careers.job_types.fulltime": "Vollzeit",
    
    // Contact page
    "contact.title": "Kontaktieren Sie uns",
    "contact.subtitle": "Haben Sie Fragen oder benötigen Sie Unterstützung? Wir sind hier, um zu helfen.",
    "contact.form.title": "Senden Sie uns eine Nachricht",
    "contact.form.name": "Name",
    "contact.form.email": "E-Mail",
    "contact.form.company": "Unternehmen",
    "contact.form.subject": "Betreff",
    "contact.form.message": "Nachricht",
    "contact.form.send": "Nachricht senden",
    "contact.get_in_touch": "Nehmen Sie Kontakt auf",
    "contact.availability": "Unser Team ist Montag bis Freitag von 9 bis 17 Uhr PT verfügbar.",
    "contact.email_us": "E-Mail an uns",
    "contact.call_us": "Rufen Sie uns an",
    "contact.visit_office": "Besuchen Sie unser Büro",
    "contact.faq.title": "Häufig gestellte Fragen",
    "contact.faq.response_time.question": "Wie schnell erhalte ich eine Antwort?",
    "contact.faq.response_time.answer": "Wir bemühen uns, auf alle Anfragen innerhalb von 24 Geschäftsstunden zu antworten.",
    "contact.faq.demos.question": "Bieten Sie Demos an?",
    "contact.faq.demos.answer": "Ja! Sie können eine persönliche Demo mit unserem Team vereinbaren, um LeadShield in Aktion zu sehen.",
    "contact.faq.pricing.question": "Wo finde ich Preisinformationen?",
    "contact.faq.pricing.answer": "Besuchen Sie unsere Preisseite oder kontaktieren Sie unser Vertriebsteam für detaillierte Preisinformationen."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  // Try to get language from localStorage, default to 'en'
  const [language, setLanguage] = useState<Language>(() => {
    const storedLanguage = localStorage.getItem('leadshield-language');
    return (storedLanguage as Language) || 
           (navigator.language.startsWith('pt') ? 'pt' : 
            navigator.language.startsWith('es') ? 'es' : 
            navigator.language.startsWith('fr') ? 'fr' : 
            navigator.language.startsWith('de') ? 'de' : 'en');
  });

  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('leadshield-language', language);
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
